In [3]:
import numpy as np
import pandas as pd

In [4]:
train = pd.read_csv("train.csv")

In [5]:
test = pd.read_csv("test.csv")

In [6]:
train.head()

,Index,geohash,day,timestamp,demand,RoadType,NumberofLanes,LargeVehicles,Landmarks,Temperature,Weather
0,0,qp02z1,48,0:0,0.048804,NaN,1,Not Allowed,No,NaN,NaN
1,1,qp02zt,48,0:0,0.118507,Residential,3,Allowed,Yes,31.104565,Sunny
2,2,qp08bj,48,0:0,0.027132,Residential,1,Not Allowed,No,25.919267,Sunny
3,3,qp08gt,48,0:0,0.003272,Residential,1,Not Allowed,No,NaN,Rainy
4,4,qp02zq,48,0:0,0.010819,Residential,1,Not Allowed,No,10.803667,Rainy

In [7]:
train.shape

(77299, 11)

In [8]:
train.columns

Index(['Index', 'geohash', 'day', 'timestamp', 'demand', 'RoadType',
       'NumberofLanes', 'LargeVehicles', 'Landmarks', 'Temperature',
       'Weather'],
      dtype='object')

In [9]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77299 entries, 0 to 77298
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Index          77299 non-null  int64
 1   geohash        77299 non-null  object
 2   day            77299 non-null  int64
 3   timestamp      77299 non-null  object
 4   demand         77299 non-null  float64
 5   RoadType       76699 non-null  object
 6   NumberofLanes  77299 non-null  int64
 7   LargeVehicles  77299 non-null  object
 8   Landmarks      77299 non-null  object
 9   Temperature    74804 non-null  float64
 10  Weather        76502 non-null  object
dtypes: float64(2), int64(3), object(6)
memory usage: 6.5+ MB

In [10]:
train.isnull().sum()

Index               0
geohash             0
day                 0
timestamp           0
demand              0
RoadType          600
NumberofLanes       0
LargeVehicles       0
Landmarks           0
Temperature      2495
Weather           797
dtype: int64

In [11]:
train["demand"].describe()

count    7.729900e+04
mean     9.394238e-02
std      1.421905e-01
min      6.245650e-07
25%      1.822723e-02
50%      4.775994e-02
75%      1.085951e-01
max      1.000000e+00
Name: demand, dtype: float64

In [1]:
test.info()

NameError: name 'test' is not defined

In [2]:
test.info

NameError: name 'test' is not defined

In [3]:
import pandas as pd
import numpy as np

In [4]:
test= pd.read_csv("test.csv")

In [5]:
train = pd.read_csv("train.csv")

In [6]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41778 entries, 0 to 41777
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Index          41778 non-null  int64
 1   geohash        41778 non-null  object
 2   day            41778 non-null  int64
 3   timestamp      41778 non-null  object
 4   RoadType       41454 non-null  object
 5   NumberofLanes  41778 non-null  int64
 6   LargeVehicles  41778 non-null  object
 7   Landmarks      41778 non-null  object
 8   Temperature    40429 non-null  float64
 9   Weather        41347 non-null  object
dtypes: float64(1), int64(3), object(6)
memory usage: 3.2+ MB

In [7]:
test.columns

Index(['Index', 'geohash', 'day', 'timestamp', 'RoadType', 'NumberofLanes',
       'LargeVehicles', 'Landmarks', 'Temperature', 'Weather'],
      dtype='object')

In [8]:
test.head()

,Index,geohash,day,timestamp,RoadType,NumberofLanes,LargeVehicles,Landmarks,Temperature,Weather
0,0,qp02z1,49,2:15,NaN,1,Not Allowed,No,NaN,NaN
1,1,qp02z9,49,2:15,Residential,1,Not Allowed,No,6.476213,Snowy
2,2,qp02yf,49,2:15,Residential,3,Allowed,Yes,22.318203,Sunny
3,3,qp02z6,49,2:15,Residential,2,Not Allowed,Yes,NaN,Rainy
4,4,qp02zd,49,2:15,Residential,1,Not Allowed,No,18.266162,Foggy

In [9]:
train.isnull().sum()

Index               0
geohash             0
day                 0
timestamp           0
demand              0
RoadType          600
NumberofLanes       0
LargeVehicles       0
Landmarks           0
Temperature      2495
Weather           797
dtype: int64

In [10]:
train["demand"].describe()

count    7.729900e+04
mean     9.394238e-02
std      1.421905e-01
min      6.245650e-07
25%      1.822723e-02
50%      4.775994e-02
75%      1.085951e-01
max      1.000000e+00
Name: demand, dtype: float64

In [11]:
test.isnull().sum()

Index               0
geohash             0
day                 0
timestamp           0
RoadType          324
NumberofLanes       0
LargeVehicles       0
Landmarks           0
Temperature      1349
Weather           431
dtype: int64

In [12]:
train.describe()

              Index           day        demand  NumberofLanes   Temperature
count  77299.000000  77299.000000  7.729900e+04   77299.000000  74804.000000
mean   38649.000000     48.101838  9.394238e-02       2.014334     16.405354
std    22314.443566      0.302438  1.421905e-01       0.904665      7.359835
min        0.000000     48.000000  6.245650e-07       1.000000    -14.935097
25%    19324.500000     48.000000  1.822723e-02       1.000000     11.430473
50%    38649.000000     48.000000  4.775994e-02       2.000000     16.382587
75%    57973.500000     48.000000  1.085951e-01       3.000000     21.298833
max    77298.000000     49.000000  1.000000e+00       5.000000     48.251433

In [13]:
weather_mode = train['Weather'].mode()[0]

In [14]:
weather_mode = train['Weather'].mode()[0]

train['Weather'] = train['Weather'].fillna(weather_mode)
test['Weather'] = test['Weather'].fillna(weather_mode)

In [15]:
train['RoadType'] = train['RoadType'].fillna('Unknown')
test['RoadType'] = test['RoadType'].fillna('Unknown')

In [16]:
for col in ['LargeVehicles', 'Landmarks']:
    train[col] = train[col].fillna(train[col].mode()[0])
    test[col] = test[col].fillna(train[col].mode()[0])

In [17]:
temperature_median = train['Temperature'].median()
train['Temperature'] = train['Temperature'].fillna(temp_median)
test['Temperature'] = test['Temperature'].fillna(temp_median)

NameError: name 'temp_median' is not defined

In [18]:
temperature_median = train['Temperature'].median()
train['Temperature'] = train['Temperature'].fillna(temperature_median)
test['Temperature'] = test['Temperature'].fillna(temperature_median)

In [19]:
train.isnull().sum()

Index            0
geohash          0
day              0
timestamp        0
demand           0
RoadType         0
NumberofLanes    0
LargeVehicles    0
Landmarks        0
Temperature      0
Weather          0
dtype: int64

In [20]:
test.isnull().sum()

Index            0
geohash          0
day              0
timestamp        0
RoadType         0
NumberofLanes    0
LargeVehicles    0
Landmarks        0
Temperature      0
Weather          0
dtype: int64

In [21]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77299 entries, 0 to 77298
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Index          77299 non-null  int64
 1   geohash        77299 non-null  object
 2   day            77299 non-null  int64
 3   timestamp      77299 non-null  object
 4   demand         77299 non-null  float64
 5   RoadType       77299 non-null  object
 6   NumberofLanes  77299 non-null  int64
 7   LargeVehicles  77299 non-null  object
 8   Landmarks      77299 non-null  object
 9   Temperature    77299 non-null  float64
 10  Weather        77299 non-null  object
dtypes: float64(2), int64(3), object(6)
memory usage: 6.5+ MB

In [1]:
hour = timestamp.split(":")[0]

NameError: name 'timestamp' is not defined

In [2]:
train['timestamp']

NameError: name 'train' is not defined

In [3]:
import pandas as pd 
import numpy as np

In [4]:
train = pd.read_csv("train.csv")

In [5]:
test = pd.read_csv("test.csv")

In [6]:
train.head()

,Index,geohash,day,timestamp,demand,RoadType,NumberofLanes,LargeVehicles,Landmarks,Temperature,Weather
0,0,qp02z1,48,0:0,0.048804,NaN,1,Not Allowed,No,NaN,NaN
1,1,qp02zt,48,0:0,0.118507,Residential,3,Allowed,Yes,31.104565,Sunny
2,2,qp08bj,48,0:0,0.027132,Residential,1,Not Allowed,No,25.919267,Sunny
3,3,qp08gt,48,0:0,0.003272,Residential,1,Not Allowed,No,NaN,Rainy
4,4,qp02zq,48,0:0,0.010819,Residential,1,Not Allowed,No,10.803667,Rainy

In [7]:
train['timestamp']

0        0:0
1        0:0
2        0:0
3        0:0
4        0:0
        ...
77294    2:0
77295    2:0
77296    2:0
77297    2:0
77298    2:0
Name: timestamp, Length: 77299, dtype: object

In [8]:
train['hour'] = train['timestamp'].apply(lambda x: int(x.split(':')[0]))
train['minute'] = train['timestamp'].apply(lambda x: int(x.split(':')[1]))

In [9]:
train['time_block'] = train['hour'] * 60 + train['minute']

In [10]:
train['is_morning_peak'] = train['hour'].isin([7, 8, 9]).astype(int)
train['is_evening_peak'] = train['hour'].isin([17,18,19]).astype(int)
train['is_night'] = train['hour'].isin([0,1,2,3,4,5]).astype(int)

In [11]:
test['hour'] = test['timestampt'].apply(lambda x: int(x.split(':')[0]))
test['minute'] = test['timestamp'].apply(lambda x: int(x.split(':')[0]))

KeyError: 'timestampt'

In [12]:
test['hour'] = test['timestamp'].apply(lambda x: int(x.split(':')[0]))
test['minute'] = test['timestamp'].apply(lambda x: int(x.split(':')[1]))

In [13]:
train['time_block'] = train['hour'] * 60 + train['minute']
test['time_block'] = test['hour'] * 60 + test['minute']

In [14]:
train['is_morning_peak'] = train['hour'].isin([7,8,9]).astype(int)
train['is_evening_peak'] = train['hour'].isin([17,18,19]).astype(int)
train['is_night'] = train['hour'].isin([0,1,2,3,4,5]).astype(int)

test['is_morning_peak'] = test['hour'].isin([7,8,9]).astype(int)
test['is_evening_peak'] = test['hour'].isin([17,18,19]).astype(int)
test['is_night'] = test['hour'].isin([0,1,2,3,4,5]).astype(int)

In [15]:
train['hour_sin'] = np.sin(2 * np.pi * train['hour'] / 24)
train['hour_cos'] = np.cos(2 * np.pi * train['hour'] / 24)

test['hour_sin'] = np.sin(2 * np.pi * test['hour'] / 24)
test['hour_cos'] = np.cos(2 * np.pi * test['hour'] / 24)

In [16]:
train[['hour','minute','time_block','hour_sin','hour_cos']].head()

   hour  minute  time_block  hour_sin  hour_cos
0     0       0           0       0.0       1.0
1     0       0           0       0.0       1.0
2     0       0           0       0.0       1.0
3     0       0           0       0.0       1.0
4     0       0           0       0.0       1.0

In [17]:
train['demand'].describe()

count    7.729900e+04
mean     9.394238e-02
std      1.421905e-01
min      6.245650e-07
25%      1.822723e-02
50%      4.775994e-02
75%      1.085951e-01
max      1.000000e+00
Name: demand, dtype: float64

In [18]:
print(train['demand'].skew())

3.7285172887316613

In [19]:
print(train['timestamop'].head(20))

KeyError: 'timestamop'

In [20]:
print(train['timestamp'].head(20))

0     0:0
1     0:0
2     0:0
3     0:0
4     0:0
5     0:0
6     0:0
7     0:0
8     0:0
9     0:0
10    0:0
11    0:0
12    0:0
13    0:0
14    0:0
15    0:0
16    0:0
17    0:0
18    0:0
19    0:0
Name: timestamp, dtype: object

In [21]:
print(train['day'].unique())

[48 49]

In [22]:
print(train['geohash'].head())

0    qp02z1
1    qp02zt
2    qp08bj
3    qp08gt
4    qp02zq
Name: geohash, dtype: object

In [23]:
print(train['geohash'].unique())

['qp02z1' 'qp02zt' 'qp08bj' ... 'qp098v' 'qp0d5c' 'qp0d55']

In [24]:
print(train['geohash'].nunique())

1249

In [25]:
print(train['timestamp'].nunique()) #this tells 24*4 , data recorded after evry 15 mins

96

In [26]:
print(train['day'].value_counts())

day
48    69427
49     7872
Name: count, dtype: int64

In [27]:
print(train['day', 'timestamp']].head(20))

SyntaxError: closing parenthesis ']' does not match opening parenthesis '(' (743456247.py, line 1)

In [28]:
print(train[['day', 'timestamp']].head(20))

    day timestamp
0    48       0:0
1    48       0:0
2    48       0:0
3    48       0:0
4    48       0:0
5    48       0:0
6    48       0:0
7    48       0:0
8    48       0:0
9    48       0:0
10   48       0:0
11   48       0:0
12   48       0:0
13   48       0:0
14   48       0:0
15   48       0:0
16   48       0:0
17   48       0:0
18   48       0:0
19   48       0:0

In [29]:
print(train['day'].nunique())

2

In [30]:
print(sorted(train['day'].unique())

SyntaxError: incomplete input (222173451.py, line 1)

In [31]:
print(sorted(train['day'].unique()))

[48, 49]

In [32]:
train['hour'] = train['timestamp'].apply(
    lambda x: int(str(x).split(':')[0])
)

train['minute'] = train['timestamp'].apply(
    lambda x: int(str(x).split(':')[1])
)

In [33]:
print(train[['timestamp', 'hour', 'minute']].head(20))

   timestamp  hour  minute
0        0:0     0       0
1        0:0     0       0
2        0:0     0       0
3        0:0     0       0
4        0:0     0       0
5        0:0     0       0
6        0:0     0       0
7        0:0     0       0
8        0:0     0       0
9        0:0     0       0
10       0:0     0       0
11       0:0     0       0
12       0:0     0       0
13       0:0     0       0
14       0:0     0       0
15       0:0     0       0
16       0:0     0       0
17       0:0     0       0
18       0:0     0       0
19       0:0     0       0

In [34]:
print(train['hour'].value_counts().sort_index())

hour
0     6338
1     6871
2     4455
3     3595
4     3683
5     3621
6     3665
7     3569
8     3507
9     3549
10    3622
11    3567
12    3525
13    3271
14    3000
15    2580
16    2108
17    1684
18    1247
19    1214
20    1418
21    1738
22    2410
23    3062
Name: count, dtype: int64

In [35]:
print(f"Day range: {train['day'].min()} to {train['day'].max()}")
print(f"Test day range: {test['day'].min()} to {test['day'].max()}")

Day range: 48 to 49
Test day range: 49 to 49

In [36]:
print(train.groupby('day')['demand'].mean())

day
48    0.092659
49    0.105262
Name: demand, dtype: float64

In [37]:
print(train.groupby(['day','hour'])['demand'].mean().unstack())

hour        0         1         2         3         4         5         6   \
day
48    0.057490  0.072637  0.083555  0.091329  0.101678  0.104368  0.103913
49    0.105352  0.105908  0.102388       NaN       NaN       NaN       NaN

hour        7         8         9   ...        14        15        16  \
day                                 ...
48    0.106198  0.106149  0.109231  ...  0.107166  0.083161  0.070065
49         NaN       NaN       NaN  ...       NaN       NaN       NaN

hour        17        18        19        20        21        22        23
day
48    0.058905  0.048787  0.042114  0.043778  0.056955  0.074544  0.092517
49         NaN       NaN       NaN       NaN       NaN       NaN       NaN

[2 rows x 24 columns]

In [38]:
train.groupby('hour')['demand'].mean()

hour
0     0.083369
1     0.089793
2     0.087368
3     0.091329
4     0.101678
5     0.104368
6     0.103913
7     0.106198
8     0.106149
9     0.109231
10    0.111602
11    0.117301
12    0.114770
13    0.116308
14    0.107166
15    0.083161
16    0.070065
17    0.058905
18    0.048787
19    0.042114
20    0.043778
21    0.056955
22    0.074544
23    0.092517
Name: demand, dtype: float64

In [39]:
train.groupby('Weather')['demand'].mean().sort_values(ascending=False)

Weather
Rainy    0.094471
Sunny    0.094247
Foggy    0.093372
Snowy    0.092581
Name: demand, dtype: float64

In [40]:
train.groupby('RoadType')['demand'].mean().sort_values(ascending=False)

RoadType
Highway        0.610756
Street         0.273164
Residential    0.057209
Name: demand, dtype: float64

In [41]:
train.groupby('NumberofLanes')['demand'].mean().sort_values(ascending=False)

NumberofLanes
5    0.607556
4    0.602882
1    0.088104
3    0.077859
2    0.077488
Name: demand, dtype: float64

In [42]:
pd.crosstab(train['RoadType'], train['NumberofLanes'])

NumberofLanes      1      2      3    4    5
RoadType
Highway            0    855    881  915  909
Residential    23269  23091  22870    0    0
Street          3909      0      0    0    0

In [43]:
train.groupby('LargeVehicles')['demand'].mean()

LargeVehicles
Allowed        0.131923
Not Allowed    0.073986
Name: demand, dtype: float64

In [44]:
pd.crosstab(train['RoadType'], train['LargeVehicles'])

LargeVehicles  Allowed  Not Allowed
RoadType
Highway           3560            0
Residential      22870        46360
Street               0         3909

In [45]:
train.groupby('Landmarks')['demand'].mean().sort_values(ascending=False)

Landmarks
No     0.096295
Yes    0.092801
Name: demand, dtype: float64

In [46]:
print("Day 48 hours:", sorted(train[train['day']==48]['hour'].unique()))
print("Day 49 hours:", sorted(train[train['day']==49]['hour'].unique()))

Day 48 hours: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
Day 49 hours: [0, 1, 2]

In [47]:
print(train['day'].value_counts())

day
48    69427
49     7872
Name: count, dtype: int64

In [48]:
print("Day 48 hour counts:")
print(train[train['day']==48]['hour'].value_counts().sort_index())

Day 48 hour counts:
hour
0     2911
1     3328
2     3553
3     3595
4     3683
5     3621
6     3665
7     3569
8     3507
9     3549
10    3622
11    3567
12    3525
13    3271
14    3000
15    2580
16    2108
17    1684
18    1247
19    1214
20    1418
21    1738
22    2410
23    3062
Name: count, dtype: int64

In [49]:
print("\nDay 49 hour counts:")
print(train[train['day']==49]['hour'].value_counts().sort_index())

Day 49 hour counts:
hour
0    3427
1    3543
2     902
Name: count, dtype: int64

In [50]:
print(train.groupby('day')['demand'].mean())

day
48    0.092659
49    0.105262
Name: demand, dtype: float64

In [51]:
train.groupby('day')['demand'].agg(['count','mean','std'])

     count      mean       std
day
48   69427  0.092659  0.141837
49    7872  0.105262  0.144792

In [52]:
test['day'].value_counts()

day
49    41778
Name: count, dtype: int64

In [53]:
print(train['geohash'].nunique())
print(test['geohash'].nunique())

print(len(set(test['geohash']) - set(train['geohash'])))

1249
1190
10

In [54]:
!pip install pygeohash

Collecting pygeohash
  Downloading pygeohash-3.3.0-cp311-cp311-win_amd64.whl.metadata (11 kB)
Downloading pygeohash-3.3.0-cp311-cp311-win_amd64.whl (35 kB)
Installing collected packages: pygeohash
Successfully installed pygeohash-3.3.0

In [55]:
import pygeohash as pgh

In [56]:
import pandas as pd

In [57]:
def decode_geohash(gh):
    lat, lon = pgh.decode(gh)
    return pd.Series([float(lat), float(lon)])

train[['lat', 'lon']]= train['geohash'].apply(decode_geohash)
test[['lat', 'lon']]= test['geohash'].apply(decode_geohash)

In [58]:
train[['geohash','lat','lon']].head()

  geohash       lat        lon
0  qp02z1 -5.484924  90.664673
1  qp02zt -5.462952  90.686646
2  qp08bj -5.462952  90.708618
3  qp08gt -5.462952  90.862427
4  qp02zq -5.457458  90.675659

In [59]:
print(train['lat'].describe())
print(train['lon'].describe())

count    77299.000000
mean        -5.348365
std          0.057688
min         -5.484924
25%         -5.391541
50%         -5.347595
75%         -5.303650
max         -5.237732
Name: lat, dtype: float64
count    77299.000000
mean        90.764108
std          0.103093
min         90.587769
25%         90.675659
50%         90.752563
75%         90.851440
max         90.972290
Name: lon, dtype: float64

In [60]:
print(train['geohash'].str.len().value_counts())

geohash
6    77299
Name: count, dtype: int64

In [61]:
print(train['geohash'].iloc[0])
print(type(train['geohash'].iloc[0]))

qp02z1
<class 'str'>

In [62]:
top_geo = train.groupby('geohash')['demand'].mean().sort_values(ascending=False)

print("Top 10 locations")
print(top_geo.head(10))

print("\nBottom 10 locations")
print(top_geo.tail(10))

Top 10 locations
geohash
qp09d9    0.960715
qp09ft    0.868850
qp09e5    0.864989
qp09d8    0.669318
qp096x    0.665630
qp09d2    0.664722
qp09dc    0.661462
qp096r    0.650468
qp09d3    0.643498
qp03xx    0.631194
Name: demand, dtype: float64

Bottom 10 locations
geohash
qp0dnh    0.001401
qp08gu    0.001348
qp03yr    0.001264
qp097p    0.001091
qp09t1    0.000984
qp09bv    0.000922
qp093h    0.000815
qp09k7    0.000793
qp08bt    0.000780
qp03zy    0.000495
Name: demand, dtype: float64

In [63]:
geo_stats = train.groupby('geohash')['demand'].agg(
    ['count','mean','std']
)

print(geo_stats.sort_values('mean', ascending=False).head(10))

         count      mean       std
geohash
qp09d9     105  0.960715  0.090041
qp09ft     105  0.868850  0.209092
qp09e5     105  0.864989  0.239612
qp09d8     105  0.669318  0.234383
qp096x     105  0.665630  0.296666
qp09d2     105  0.664722  0.334164
qp09dc     105  0.661462  0.368198
qp096r     105  0.650468  0.344110
qp09d3     105  0.643498  0.295267
qp03xx     105  0.631194  0.346098

In [64]:
print(train.groupby('RoadType')['geohash'].nunique())

RoadType
Highway         131
Residential    1246
Street          254
Name: geohash, dtype: int64

In [65]:
# Historical average demand at each location
geo_stats = train.groupby('geohash')['demand'].agg(
    ['mean','median','std','max']
)

In [66]:
print(geo_stats.head())

             mean    median       std       max
geohash
qp02yc   0.018498  0.019071  0.012374  0.046790
qp02yf   0.029433  0.029433       NaN  0.029433
qp02yy   0.002902  0.002902  0.001435  0.003916
qp02yz   0.036564  0.034495  0.022065  0.111003
qp02z1   0.040048  0.035383  0.030124  0.116299

In [67]:
geo_stats.columns = [
    'geo_mean',
    'geo_median',
    'geo_std',
    'geo_max'
]

print(geo_stats.head())

         geo_mean  geo_median   geo_std   geo_max
geohash
qp02yc   0.018498    0.019071  0.012374  0.046790
qp02yf   0.029433    0.029433       NaN  0.029433
qp02yy   0.002902    0.002902  0.001435  0.003916
qp02yz   0.036564    0.034495  0.022065  0.111003
qp02z1   0.040048    0.035383  0.030124  0.116299

In [68]:
train = train.join(
    geo_stats,
    on='geohash'
)

In [69]:
test = test.join(
    geo_stats,
    on='geohash'
)

In [70]:
print(test[['geo_mean',
            'geo_median',
            'geo_std',
            'geo_max']].isnull().sum())

geo_mean      25
geo_median    25
geo_std       42
geo_max       25
dtype: int64

In [71]:
test['geo_mean'] = test['geo_mean'].fillna(
    train['demand'].mean()
)

test['geo_median'] = test['geo_median'].fillna(
    train['demand'].median()
)

test['geo_std'] = test['geo_std'].fillna(
    train['demand'].std()
)

test['geo_max'] = test['geo_max'].fillna(
    train['demand'].max()
)

In [72]:
print(train[['geohash',
             'geo_mean',
             'geo_median',
             'geo_std',
             'geo_max']].head())

  geohash  geo_mean  geo_median   geo_std   geo_max
0  qp02z1  0.040048    0.035383  0.030124  0.116299
1  qp02zt  0.208766    0.213870  0.102870  0.424569
2  qp08bj  0.127931    0.116483  0.073696  0.332333
3  qp08gt  0.014381    0.012175  0.010206  0.037525
4  qp02zq  0.029300    0.025936  0.025563  0.116787

In [73]:
print(test[['geo_mean',
            'geo_median',
            'geo_std',
            'geo_max']].isnull().sum())

geo_mean      0
geo_median    0
geo_std       0
geo_max       0
dtype: int64

In [74]:
# Average traffic demand for each location-hour combination
geo_hour_mean = train.groupby(
    ['geohash', 'hour']
)['demand'].mean()

train['geo_hour_mean'] = (
    train.set_index(['geohash', 'hour'])
         .index
         .map(geo_hour_mean)
)

test['geo_hour_mean'] = (
    test.set_index(['geohash', 'hour'])
        .index
        .map(geo_hour_mean)
)

test['geo_hour_mean'] = test['geo_hour_mean'].fillna(
    train['demand'].mean()
)

In [75]:
print(train[['geohash','hour','geo_hour_mean']].head(10))
print(test['geo_hour_mean'].isnull().sum())

  geohash  hour  geo_hour_mean
0  qp02z1     0       0.034855
1  qp02zt     0       0.140998
2  qp08bj     0       0.068046
3  qp08gt     0       0.011243
4  qp02zq     0       0.020746
5  qp02zw     0       0.070476
6  qp02zy     0       0.080202
7  qp08by     0       0.034679
8  qp08gq     0       0.014898
9  qp08gy     0       0.003118
0

In [76]:
print(train[train['day']==48]['hour'].value_counts().sort_index())

print(train[train['day']==49]['hour'].value_counts().sort_index())

hour
0     2911
1     3328
2     3553
3     3595
4     3683
5     3621
6     3665
7     3569
8     3507
9     3549
10    3622
11    3567
12    3525
13    3271
14    3000
15    2580
16    2108
17    1684
18    1247
19    1214
20    1418
21    1738
22    2410
23    3062
Name: count, dtype: int64
hour
0    3427
1    3543
2     902
Name: count, dtype: int64

In [77]:
pd.crosstab(
    train['day'],
    train['hour']
)

hour,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
day,,,,,,,,,,,,,,,,,,,,,
48,2911,3328,3553,3595,3683,3621,3665,3569,3507,3549,...,3000,2580,2108,1684,1247,1214,1418,1738,2410,3062
49,3427,3543,902,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [78]:
hour	0	1	2	3	4	5	6	7	8	9	...	14	15	16	17	18	19	20	21	22	23
day																					
48	2911	3328	3553	3595	3683	3621	3665	3569	3507	3549	...	3000	2580	2108	1684	1247	1214	1418	1738	2410	3062
49	3427	3543	902	0	0	0	0	0	0	0	...	0	0	0	0	0	0	0	0	0	0

SyntaxError: invalid syntax (1171234670.py, line 1)

In [79]:
print(
    train[train['day']==49]['timestamp'].value_counts().sort_index()
)

timestamp
0:0     842
0:15    864
0:30    870
0:45    851
1:0     868
1:15    880
1:30    899
1:45    896
2:0     902
Name: count, dtype: int64

In [80]:
print(test['hour'].value_counts().sort_index())

hour
2     2698
3     3610
4     3725
5     3699
6     3596
7     3577
8     3561
9     3628
10    3568
11    3514
12    3415
13    3187
Name: count, dtype: int64

In [81]:
test['hour'] = test['timestamp'].apply(
    lambda x: int(str(x).split(':')[0])
)

print(test['hour'].value_counts().sort_index())

hour
2     2698
3     3610
4     3725
5     3699
6     3596
7     3577
8     3561
9     3628
10    3568
11    3514
12    3415
13    3187
Name: count, dtype: int64

In [82]:
train['time_block'] = train['hour'] * 4 + train['minute']//15
test['time_block'] = test['hour'] * 4 + test['minute']//15

In [83]:
#focuses on time.
block_mean = train.groupby('time_block')['demand'].mean()

train['block_mean_demand'] = train['time_block'].map(block_mean)
test['block_mean_demand'] = test['time_block'].map(block_mean)

In [84]:
train.groupby('hour')['demand'].agg(
    ['mean','std','count']
)

          mean       std  count
hour
0     0.083369  0.122252   6338
1     0.089793  0.126183   6871
2     0.087368  0.120569   4455
3     0.091329  0.127422   3595
4     0.101678  0.142908   3683
5     0.104368  0.146397   3621
6     0.103913  0.148054   3665
7     0.106198  0.152324   3569
8     0.106149  0.156256   3507
9     0.109231  0.162241   3549
10    0.111602  0.164237   3622
11    0.117301  0.169780   3567
12    0.114770  0.170508   3525
13    0.116308  0.179685   3271
14    0.107166  0.169965   3000
15    0.083161  0.135628   2580
16    0.070065  0.120829   2108
17    0.058905  0.114608   1684
18    0.048787  0.098401   1247
19    0.042114  0.088730   1214
20    0.043778  0.086971   1418
21    0.056955  0.082345   1738
22    0.074544  0.099493   2410
23    0.092517  0.128378   3062

In [85]:
train.groupby('RoadType')['demand'].agg(
    ['mean','std','count']
)

                 mean       std  count
RoadType
Highway      0.610756  0.229419   3560
Residential  0.057209  0.052057  69230
Street       0.273164  0.036693   3909

In [86]:
train.groupby('hour')['demand'].agg(
    ['mean','std','min','max']
)

          mean       std           min  max
hour
0     0.083369  0.122252  3.896741e-06  1.0
1     0.089793  0.126183  4.833052e-06  1.0
2     0.087368  0.120569  7.981559e-07  1.0
3     0.091329  0.127422  2.641018e-05  1.0
4     0.101678  0.142908  8.331217e-06  1.0
5     0.104368  0.146397  3.640839e-05  1.0
6     0.103913  0.148054  1.906448e-05  1.0
7     0.106198  0.152324  1.990684e-05  1.0
8     0.106149  0.156256  8.914735e-05  1.0
9     0.109231  0.162241  2.192115e-05  1.0
10    0.111602  0.164237  1.189018e-05  1.0
11    0.117301  0.169780  2.883754e-05  1.0
12    0.114770  0.170508  4.995530e-05  1.0
13    0.116308  0.179685  6.514998e-06  1.0
14    0.107166  0.169965  7.398574e-06  1.0
15    0.083161  0.135628  2.967152e-05  1.0
16    0.070065  0.120829  2.237335e-05  1.0
17    0.058905  0.114608  3.465328e-05  1.0
18    0.048787  0.098401  6.245650e-07  1.0
19    0.042114  0.088730  5.804771e-06  1.0
20    0.043778  0.086971  1.985902e-05  1.0
21    0.056955  0.082345  4.706162e-05  1.0
22    0.074544  0.099493  7.022824e-05  1.0
23    0.092517  0.128378  9.980109e-06  1.0

In [87]:
train.groupby(['RoadType','hour'])['demand'].mean().unstack()

hour,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
RoadType,,,,,,,,,,,,,,,,,,,,,
Highway,0.561809,0.565261,0.559365,0.568663,0.586614,0.605216,0.617390,0.636852,0.632307,0.645554,...,0.662563,0.621487,0.580253,0.607297,0.792079,0.717534,0.682306,0.631266,0.536582,0.561879
Residential,0.054520,0.058194,0.059609,0.059994,0.062093,0.062546,0.062551,0.063589,0.062966,0.063253,...,0.056639,0.050712,0.044545,0.037937,0.034573,0.031491,0.033035,0.047146,0.054682,0.059026
Street,0.273934,0.274616,0.272234,0.264126,0.269013,0.272907,0.272421,0.279034,0.277388,0.270858,...,0.271571,0.272747,0.277290,0.273376,0.262480,0.271416,0.275924,0.263333,0.272379,0.273251

In [88]:
road_hour_mean = train.groupby(
    ['RoadType','hour']
)['demand'].mean()

train['road_hour_mean'] = train.set_index(
    ['RoadType','hour']
).index.map(road_hour_mean)

test['road_hour_mean'] = test.set_index(
    ['RoadType','hour']
).index.map(road_hour_mean)

In [89]:
train.groupby('RoadType')['geohash'].count()

RoadType
Highway         3560
Residential    69230
Street          3909
Name: geohash, dtype: int64

In [90]:
train.groupby('RoadType')['demand'].agg(
    ['mean','std','min','max']
)

                 mean       std           min       max
RoadType
Highway      0.610756  0.229419  3.500089e-01  1.000000
Residential  0.057209  0.052057  6.245650e-07  0.219997
Street       0.273164  0.036693  2.200159e-01  0.349908

In [1]:
train.head()
train.info()
test.head()

NameError: name 'train' is not defined

In [2]:
import pandas as pd

In [3]:
import numpy as np

In [4]:

train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")

In [5]:
train.head()
train.info()
test.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77299 entries, 0 to 77298
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Index          77299 non-null  int64
 1   geohash        77299 non-null  object
 2   day            77299 non-null  int64
 3   timestamp      77299 non-null  object
 4   demand         77299 non-null  float64
 5   RoadType       76699 non-null  object
 6   NumberofLanes  77299 non-null  int64
 7   LargeVehicles  77299 non-null  object
 8   Landmarks      77299 non-null  object
 9   Temperature    74804 non-null  float64
 10  Weather        76502 non-null  object
dtypes: float64(2), int64(3), object(6)
memory usage: 6.5+ MB

,Index,geohash,day,timestamp,RoadType,NumberofLanes,LargeVehicles,Landmarks,Temperature,Weather
0,0,qp02z1,49,2:15,NaN,1,Not Allowed,No,NaN,NaN
1,1,qp02z9,49,2:15,Residential,1,Not Allowed,No,6.476213,Snowy
2,2,qp02yf,49,2:15,Residential,3,Allowed,Yes,22.318203,Sunny
3,3,qp02z6,49,2:15,Residential,2,Not Allowed,Yes,NaN,Rainy
4,4,qp02zd,49,2:15,Residential,1,Not Allowed,No,18.266162,Foggy

In [6]:
train.isnull().sum()
test.isnull().sum()

Index               0
geohash             0
day                 0
timestamp           0
RoadType          324
NumberofLanes       0
LargeVehicles       0
Landmarks           0
Temperature      1349
Weather           431
dtype: int64

In [7]:
train['Temperature'] = train['Temperature'].fillna(train['Temperature'].median())
train['Weather'] = train['Weather'].fillna(train['Weather'].mode()[0])
train['RoadType'] = train['RoadType'].fillna("Unknown")

test['Temperature'] = test['Temperature'].fillna(train['Temperature'].median())
test['Weather'] = test['Weather'].fillna(train['Weather'].mode()[0])
test['RoadType'] = test['RoadType'].fillna("Unknown")

In [8]:
#extracting time features 
train['hour'] = train['timestamp'].apply(lambda x: int(x.split(':')[0]))
train['minute'] = train['timestamp'].apply(lambda x: int(x.split(':')[1]))

test['hour'] = test['timestamp'].apply(lambda x: int(x.split(':')[0]))
test['minute'] = test['timestamp'].apply(lambda x: int(x.split(':')[1]))

In [9]:
#cyclic encoding 
import numpy as np

train['hour_sin'] = np.sin(2 * np.pi * train['hour'] / 24)
train['hour_cos'] = np.cos(2 * np.pi * train['hour'] / 24)

test['hour_sin'] = np.sin(2 * np.pi * test['hour'] / 24)
test['hour_cos'] = np.cos(2 * np.pi * test['hour'] / 24)

In [10]:
#Geohash-lat/lon
import pygeohash as pgh

def decode(gh):
    try:
        lat, lon = pgh.decode(gh)
        return pd.Series([lat, lon])
    except:
        return pd.Series([0, 0])

train[['lat', 'lon']] = train['geohash'].apply(decode)
test[['lat', 'lon']] = test['geohash'].apply(decode)

In [11]:
#geo feature 
geo_mean = train.groupby('geohash')['demand'].mean()

train['geo_mean_demand'] = train['geohash'].map(geo_mean)
test['geo_mean_demand'] = test['geohash'].map(geo_mean)

test['geo_mean_demand'] = test['geo_mean_demand'].fillna(train['demand'].mean())

In [12]:
# final check of missing values 
train.isnull().sum()
test.isnull().sum()

Index              0
geohash            0
day                0
timestamp          0
RoadType           0
NumberofLanes      0
LargeVehicles      0
Landmarks          0
Temperature        0
Weather            0
hour               0
minute             0
hour_sin           0
hour_cos           0
lat                0
lon                0
geo_mean_demand    0
dtype: int64

In [13]:
# defining features 
features = [
    'hour', 'minute',
    'hour_sin', 'hour_cos',
    'lat', 'lon',
    'RoadType', 'Weather', 'LargeVehicles', 'Landmarks',
    'NumberofLanes',
    'Temperature',
    'geo_mean_demand'
]

In [14]:
#Split data(validation set)
from sklearn.model_selection import train_test_split

X = train[features]
y = train['demand']

X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [15]:
import xgboost asxgb 
from sklearn.metrics import r2_score

SyntaxError: invalid syntax (2990780682.py, line 1)

In [16]:
# training first model (XGBOOST BASELINE)
import xgboost as xgb
from sklearn.metrics import r2_score

ModuleNotFoundError: No module named 'xgboost'

In [17]:
!pip install xgboost

Collecting xgboost
  Downloading xgboost-3.2.0-py3-none-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in C:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\site-packages (from xgboost) (1.26.4)
Requirement already satisfied: scipy in C:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\site-packages (from xgboost) (1.17.1)
Downloading xgboost-3.2.0-py3-none-win_amd64.whl (101.7 MB)
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.8/101.7 MB 2.6 MB/s eta 0:00:40
    --------------------------------------- 1.6/101.7 MB 3.0 MB/s eta 0:00:34
    --------------------------------------- 2.4/101.7 MB 3.3 MB/s eta 0:00:31
   - -------------------------------------- 3.4/101.7 MB 3.7 MB/s eta 0:00:27
   - -------------------------------------- 4.5/101.7 MB 3.9 MB/s eta 0:00:25
   -- ------------------------------------- 5.8/101.7 MB 4.3 MB/s eta 0:00:23
   -- ------------------------------------- 7.1/101.7 MB 4.6 MB/s eta 0:00:21
   --- ------------------------------------ 8.7/101.7 MB 4.9 MB/s eta 0:00:20
   --- ------------------------------------ 9.7/101.7 MB 4.9 MB/s eta 0:00:19
   ---- ----------------------------------- 11.5/101.7 MB 5.2 MB/s eta 0:00:18
   ----- ---------------------------------- 12.8/101.7 MB 5.4 MB/s eta 0:00:17
   ----- ---------------------------------- 14.7/101.7 MB 5.6 MB/s eta 0:00:16
   ------ --------------------------------- 16.3/101.7 MB 5.8 MB/s eta 0:00:15
   ------- -------------------------------- 18.4/101.7 MB 6.0 MB/s eta 0:00:14
   ------- -------------------------------- 20.2/101.7 MB 6.2 MB/s eta 0:00:14
   -------- ------------------------------- 22.0/101.7 MB 6.4 MB/s eta 0:00:13
   --------- ------------------------------ 23.9/101.7 MB 6.5 MB/s eta 0:00:12
   --------- ------------------------------ 25.2/101.7 MB 6.5 MB/s eta 0:00:12
   ---------- ----------------------------- 27.0/101.7 MB 6.6 MB/s eta 0:00:12
   ---------- ----------------------------- 27.3/101.7 MB 6.4 MB/s eta 0:00:12
   ----------- ---------------------------- 29.1/101.7 MB 6.4 MB/s eta 0:00:12
   ------------ --------------------------- 30.9/101.7 MB 6.5 MB/s eta 0:00:11
   ------------ --------------------------- 32.5/101.7 MB 6.6 MB/s eta 0:00:11
   ------------- -------------------------- 34.1/101.7 MB 6.6 MB/s eta 0:00:11
   -------------- ------------------------- 36.2/101.7 MB 6.8 MB/s eta 0:00:10
   -------------- ------------------------- 38.0/101.7 MB 6.8 MB/s eta 0:00:10
   --------------- ------------------------ 40.1/101.7 MB 6.9 MB/s eta 0:00:09
   ---------------- ----------------------- 41.7/101.7 MB 7.0 MB/s eta 0:00:09
   ----------------- ---------------------- 43.5/101.7 MB 7.0 MB/s eta 0:00:09
   ----------------- ---------------------- 45.1/101.7 MB 7.0 MB/s eta 0:00:09
   ------------------ --------------------- 47.2/101.7 MB 7.1 MB/s eta 0:00:08
   ------------------- -------------------- 48.8/101.7 MB 7.1 MB/s eta 0:00:08
   ------------------- -------------------- 50.6/101.7 MB 7.1 MB/s eta 0:00:08
   -------------------- ------------------- 52.2/101.7 MB 7.1 MB/s eta 0:00:07
   --------------------- ------------------ 54.0/101.7 MB 7.2 MB/s eta 0:00:07
   --------------------- ------------------ 55.8/101.7 MB 7.2 MB/s eta 0:00:07
   ---------------------- ----------------- 57.9/101.7 MB 7.3 MB/s eta 0:00:06
   ----------------------- ---------------- 59.2/101.7 MB 7.3 MB/s eta 0:00:06
   ------------------------ --------------- 61.1/101.7 MB 7.3 MB/s eta 0:00:06
   ------------------------ --------------- 63.2/101.7 MB 7.4 MB/s eta 0:00:06
   ------------------------- -------------- 64.7/101.7 MB 7.4 MB/s eta 0:00:06
   -------------------------- ------------- 66.6/101.7 MB 7.4 MB/s eta 0:00:05
   -------------------------- ------------- 68.2/101.7 MB 7.4 MB/s eta 0:00:05
   --------------------------- ------------ 70.0/101.7 MB 7.4 MB/s eta 0:00:05
   ---------------------------- ----------- 71.8/101.7 MB 7.4 MB/s eta 0:00:05
   ----------------------------- ---------- 73.9/101.7 MB 7.5 MB/s eta 0:00:04
   ----------------------------- ---------- 75.8/101.7 MB 7.5 MB/s eta 0:00:04
   ------------------------------ --------- 77.6/101.7 MB 7.5 MB/s eta 0:00:04
   ------------------------------- -------- 79.4/101.7 MB 7.5 MB/s eta 0:00:03
   ------------------------------- -------- 81.3/101.7 MB 7.6 MB/s eta 0:00:03
   -------------------------------- ------- 82.8/101.7 MB 7.6 MB/s eta 0:00:03
   --------------------------------- ------ 84.9/101.7 MB 7.6 MB/s eta 0:00:03
   ---------------------------------- ----- 86.5/101.7 MB 7.6 MB/s eta 0:00:02
   ---------------------------------- ----- 88.3/101.7 MB 7.6 MB/s eta 0:00:02
   ----------------------------------- ---- 90.4/101.7 MB 7.7 MB/s eta 0:00:02
   ----------------------------------- ---- 91.5/101.7 MB 7.6 MB/s eta 0:00:02
   ------------------------------------ --- 93.1/101.7 MB 7.6 MB/s eta 0:00:02
   ------------------------------------- -- 94.1/101.7 MB 7.6 MB/s eta 0:00:01
   ------------------------------------- -- 95.4/101.7 MB 7.6 MB/s eta 0:00:01
   -------------------------------------- - 96.7/101.7 MB 7.5 MB/s eta 0:00:01
   -------------------------------------- - 98.0/101.7 MB 7.5 MB/s eta 0:00:01
   ---------------------------------------  99.4/101.7 MB 7.5 MB/s eta 0:00:01
   ---------------------------------------  100.7/101.7 MB 7.5 MB/s eta 0:00:01
   ---------------------------------------  101.4/101.7 MB 7.5 MB/s eta 0:00:01
   ---------------------------------------  101.4/101.7 MB 7.5 MB/s eta 0:00:01
   ---------------------------------------  101.4/101.7 MB 7.5 MB/s eta 0:00:01
   ---------------------------------------- 101.7/101.7 MB 7.1 MB/s  0:00:14
Installing collected packages: xgboost
Successfully installed xgboost-3.2.0

In [18]:
import xgboost as xgb

In [19]:
from sklearn.metrics import r2_score

In [20]:
import xgboost as xgb
from sklearn.metrics import r2_score

In [21]:
#training first model 
model = xgb.XGBRegressor(
    n_estimators=500,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

model.fit(X_train, y_train)

ValueError: DataFrame.dtypes for data must be int, float, bool or category. When categorical type is supplied, the experimental DMatrix parameter`enable_categorical` must be set to `True`.  Invalid columns:RoadType: object, Weather: object, LargeVehicles: object, Landmarks: object

In [22]:
from sklearn.preprocessing import LabelEncoder

cat_cols = ['RoadType', 'Weather', 'LargeVehicles', 'Landmarks']

for col in cat_cols:
    le = LabelEncoder()
    
    combined = pd.concat([train[col], test[col]]).astype(str)
    le.fit(combined)
    
    train[col] = le.transform(train[col].astype(str))
    test[col] = le.transform(test[col].astype(str))

In [23]:
train[cat_cols].dtypes

RoadType         int32
Weather          int32
LargeVehicles    int32
Landmarks        int32
dtype: object

In [24]:
model.fit(X_train, y_train)

ValueError: DataFrame.dtypes for data must be int, float, bool or category. When categorical type is supplied, the experimental DMatrix parameter`enable_categorical` must be set to `True`.  Invalid columns:RoadType: object, Weather: object, LargeVehicles: object, Landmarks: object

In [25]:
features = [
    'hour', 'minute',
    'hour_sin', 'hour_cos',
    'lat', 'lon',
    'RoadType', 'Weather', 'LargeVehicles', 'Landmarks',
    'NumberofLanes',
    'Temperature',
    'geo_mean_demand'
]

X = train[features]
y = train['demand']

In [26]:
from sklearn.preprocessing import LabelEncoder

cat_cols = ['RoadType', 'Weather', 'LargeVehicles', 'Landmarks']

for col in cat_cols:
    le = LabelEncoder()
    
    combined = pd.concat([train[col], test[col]]).astype(str)
    le.fit(combined)

    train[col] = le.transform(train[col].astype(str))
    test[col] = le.transform(test[col].astype(str))

In [27]:
X = train[features]
y = train['demand']

In [28]:
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [29]:
model.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=500,
             n_jobs=None, num_parallel_tree=None, ...)

In [30]:
model.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=500,
             n_jobs=None, num_parallel_tree=None, ...)

In [31]:
val_preds = model.predict(X_val)

In [32]:
from sklearn.metrics import r2_score

score = r2_score(y_val, val_preds)
print("R2 Score:", score)
print("Leaderboard Approx:", score * 100)

R2 Score: 0.9444185911276888
Leaderboard Approx: 94.44185911276888

In [33]:
 test_preds = model.predict(test[features])

In [34]:
submission = pd.DataFrame({
    'Index': test['Index'],
    'demand': test_preds
})

submission.to_csv("submission.csv", index=False)
print(submission.head())
print(submission.shape)

   Index    demand
0      0  0.058356
1      1  0.028943
2      2  0.027735
3      3  0.034533
4      4  0.057791
(41778, 2)

In [35]:
 #Check what split you're using
print("Your validation set day distribution:")
print(y_val.index)  # or however you split

# The CORRECT split for this dataset
X_tr  = train[train['day']==48][FEATURES]
y_tr  = train[train['day']==48]['demand']
X_val = train[train['day']==49][FEATURES]
y_val = train[train['day']==49]['demand']

model.fit(X_tr, y_tr)
preds = model.predict(X_val)
print(f"DAY-BASED R²: {r2_score(y_val, preds):.4f}")

IndentationError: unexpected indent (1955555952.py, line 1)

In [36]:
 #Check what split you're using
print("Your validation set day distribution:")
print(y_val.index)  # or however you split

# The CORRECT split for this dataset
X_tr  = train[train['day']==48][FEATURES]
y_tr  = train[train['day']==48]['demand']
X_val = train[train['day']==49][FEATURES]
y_val = train[train['day']==49]['demand']

model.fit(X_tr, y_tr)
preds = model.predict(X_val)
print(f"DAY-BASED R²: {r2_score(y_val, preds):.4f}")

Your validation set day distribution:
Index([65165, 58878,  6000, 27540, 70232, 72393, 74279, 71876,   630,   652,
       ...
       59937, 75081, 28701, 54070, 72207, 54590, 23627, 47265, 20665, 74708],
      dtype='int64', length=15460)

NameError: name 'FEATURES' is not defined

In [37]:
features = [
    'hour',
    'minute',
    'time_block',
    'hour_sin',
    'hour_cos',
    'NumberofLanes',
    'Temperature',
    'RoadType',
    'Weather',
    'LargeVehicles',
    'Landmarks'
]

In [38]:
print(train['day'].value_counts())

day
48    69427
49     7872
Name: count, dtype: int64

In [39]:
X_tr = train[train['day'] == 48][features]
y_tr = train[train['day'] == 48]['demand']

X_val = train[train['day'] == 49][features]
y_val = train[train['day'] == 49]['demand']

KeyError: "['time_block'] not in index"

In [ ]:
cat_cols = ['RoadType', 'Weather', 'LargeVehicles', 'Landmarks']

for col in cat_cols:
    X_tr[col] = X_tr[col].astype('category').cat.codes
    X_val[col] = X_val[col].astype('category').cat.codes

In [40]:
import numpy as np

train['hour'] = train['timestamp'].apply(lambda x: int(x.split(':')[0]))
train['minute'] = train['timestamp'].apply(lambda x: int(x.split(':')[1]))

train['time_block'] = train['hour'] * 4 + train['minute'] // 15

train['hour_sin'] = np.sin(2 * np.pi * train['hour'] / 24)
train['hour_cos'] = np.cos(2 * np.pi * train['hour'] / 24)

In [41]:
test['hour'] = test['timestamp'].apply(lambda x: int(x.split(':')[0]))
test['minute'] = test['timestamp'].apply(lambda x: int(x.split(':')[1]))

test['time_block'] = test['hour'] * 4 + test['minute'] // 15

test['hour_sin'] = np.sin(2 * np.pi * test['hour'] / 24)
test['hour_cos'] = np.cos(2 * np.pi * test['hour'] / 24)

In [42]:
features = [
    'hour',
    'minute',
    'time_block',
    'hour_sin',
    'hour_cos',
    'NumberofLanes',
    'Temperature',
    'RoadType',
    'Weather',
    'LargeVehicles',
    'Landmarks'
]

In [43]:
X_tr = train[train['day'] == 48][features]
y_tr = train[train['day'] == 48]['demand']

X_val = train[train['day'] == 49][features]
y_val = train[train['day'] == 49]['demand']

In [44]:
train[['hour','minute','time_block','hour_sin','hour_cos']].head()

   hour  minute  time_block  hour_sin  hour_cos
0     0       0           0       0.0       1.0
1     0       0           0       0.0       1.0
2     0       0           0       0.0       1.0
3     0       0           0       0.0       1.0
4     0       0           0       0.0       1.0

In [45]:
cat_cols = ['RoadType', 'Weather', 'LargeVehicles', 'Landmarks']

for col in cat_cols:
    train[col] = train[col].astype('category').cat.codes
    test[col] = test[col].astype('category').cat.codes

In [46]:
features = [
    'hour',
    'minute',
    'time_block',
    'hour_sin',
    'hour_cos',
    'NumberofLanes',
    'Temperature',
    'RoadType',
    'Weather',
    'LargeVehicles',
    'Landmarks'
]

In [47]:
X_tr = train[train['day'] == 48][features]
y_tr = train[train['day'] == 48]['demand']

X_val = train[train['day'] == 49][features]
y_val = train[train['day'] == 49]['demand']

In [48]:
model.fit(X_tr, y_tr)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=500,
             n_jobs=None, num_parallel_tree=None, ...)

In [49]:
from sklearn.metrics import r2_score

preds = model.predict(X_val)
print("DAY SPLIT R2:", r2_score(y_val, preds))

DAY SPLIT R2: 0.7288411403549391

In [50]:
train['lat'] = train['geohash'].apply(lambda x: hash(x) % 1000)
train['lon'] = train['geohash'].apply(lambda x: hash(x[::-1]) % 1000)
test['lat'] = test['geohash'].apply(lambda x: hash(x) % 1000)
test['lon'] = test['geohash'].apply(lambda x: hash(x[::-1]) % 1000)

In [51]:
train['lag_1'] = train.groupby(['geohash', 'hour'])['demand'].shift(1)
train['lag_1'].fillna(train['demand'].mean(), inplace=True)

C:\Users\DELL\AppData\Local\Temp\ipykernel_25512\2931333373.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train['lag_1'].fillna(train['demand'].mean(), inplace=True)

In [52]:
train['lag_1'] = train['lag_1'].fillna(train['demand'].mean())

In [53]:
test['lag_1'] = test['lag_1'].fillna(train['demand'].mean())

KeyError: 'lag_1'

In [54]:
train = train.sort_values(['geohash', 'hour'])

train['lag_1'] = train.groupby(['geohash'])['demand'].shift(1)

In [55]:
train['lag_1'] = train['lag_1'].fillna(train['demand'].mean())

In [56]:
lag_map = train.groupby(['geohash', 'hour'])['demand'].mean().reset_index()
lag_map = lag_map.rename(columns={'demand': 'lag_1'})

In [57]:
test = test.merge(lag_map, on=['geohash', 'hour'], how='left')

In [58]:
test['lag_1'] = test['lag_1'].fillna(train['demand'].mean())

In [59]:
model.fit(X_tr, y_tr)
preds = model.predict(X_val)
print(r2_score(y_val, preds))

0.7288411403549391

In [1]:
train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")

NameError: name 'pd' is not defined

In [1]:
import pandas as pd
import numpy as np

In [2]:
train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")

In [3]:
print(train.shape)
print(test.shape)

print(train.head())
print(train.info())

(77299, 11)
(41778, 10)
   Index geohash  day timestamp    demand     RoadType  NumberofLanes  \
0      0  qp02z1   48       0:0  0.048804          NaN              1
1      1  qp02zt   48       0:0  0.118507  Residential              3
2      2  qp08bj   48       0:0  0.027132  Residential              1
3      3  qp08gt   48       0:0  0.003272  Residential              1
4      4  qp02zq   48       0:0  0.010819  Residential              1

  LargeVehicles Landmarks  Temperature Weather
0   Not Allowed        No          NaN     NaN
1       Allowed       Yes    31.104565   Sunny
2   Not Allowed        No    25.919267   Sunny
3   Not Allowed        No          NaN   Rainy
4   Not Allowed        No    10.803667   Rainy
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77299 entries, 0 to 77298
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Index          77299 non-null  int64
 1   geohash        77299 non-null  object
 2   day            77299 non-null  int64
 3   timestamp      77299 non-null  object
 4   demand         77299 non-null  float64
 5   RoadType       76699 non-null  object
 6   NumberofLanes  77299 non-null  int64
 7   LargeVehicles  77299 non-null  object
 8   Landmarks      77299 non-null  object
 9   Temperature    74804 non-null  float64
 10  Weather        76502 non-null  object
dtypes: float64(2), int64(3), object(6)
memory usage: 6.5+ MB
None

In [4]:
train['Temperature'] = train['Temperature'].fillna(train['Temperature'].median())
test['Temperature'] = test['Temperature'].fillna(train['Temperature'].median())

train['Weather'] = train['Weather'].fillna(train['Weather'].mode()[0])
test['Weather'] = test['Weather'].fillna(train['Weather'].mode()[0])

train['RoadType'] = train['RoadType'].fillna("Unknown")
test['RoadType'] = test['RoadType'].fillna("Unknown")

In [6]:
# Timestamp features 
train['hour'] = train['timestamp'].apply(lambda x: int(x.split(':')[0]))
train['minute'] = train['timestamp'].apply(lambda x: int(x.split(':')[1]))

test['hour'] = test['timestamp'].apply(lambda x: int(x.split(':')[0]))
test['minute'] = test['timestamp'].apply(lambda x: int(x.split(':')[1]))

train['time_block'] = train['hour'] * 4 + train['minute'] // 15
test['time_block'] = test['hour'] * 4 + test['minute'] // 15

In [7]:
#WGeohash
import pygeohash as pgh

def decode(gh):
    lat, lon = pgh.decode(gh)
    return pd.Series([lat, lon])

train[['lat', 'lon']] = train['geohash'].apply(decode)
test[['lat', 'lon']] = test['geohash'].apply(decode)

In [8]:
#lag feature 
lag_map = train.groupby(['geohash', 'time_block'])['demand'].mean()

train['lag_1'] = train.set_index(['geohash', 'time_block']).index.map(lag_map)
test['lag_1'] = test.set_index(['geohash', 'time_block']).index.map(lag_map)

train['lag_1'] = train['lag_1'].fillna(train['demand'].mean())
test['lag_1'] = test['lag_1'].fillna(train['demand'].mean())

In [9]:
# encoding categorical columns
from sklearn.preprocessing import LabelEncoder

for col in ['RoadType', 'Weather', 'LargeVehicles', 'Landmarks']:
    le = LabelEncoder()
    combined = pd.concat([train[col], test[col]]).astype(str)
    le.fit(combined)

    train[col] = le.transform(train[col].astype(str))
    test[col] = le.transform(test[col].astype(str))

In [10]:
features = [
    'hour', 'minute', 'time_block',
    'lat', 'lon',
    'RoadType', 'Weather', 'LargeVehicles', 'Landmarks',
    'NumberofLanes',
    'Temperature',
    'lag_1'
]

In [11]:
#Train and validation split 
X_tr = train[train['day'] == 48][features]
y_tr = train[train['day'] == 48]['demand']

X_val = train[train['day'] == 49][features]
y_val = train[train['day'] == 49]['demand']

In [12]:
#Model training
import xgboost as xgb
from sklearn.metrics import r2_score

model = xgb.XGBRegressor(
    n_estimators=500,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

model.fit(X_tr, y_tr)

preds = model.predict(X_val)

print("R2 Score:", r2_score(y_val, preds))

R2 Score: 0.741424268495842

In [13]:
#Adding Geo Mean Feature 
geo_mean = train.groupby('geohash')['demand'].mean()

train['geo_mean'] = train['geohash'].map(geo_mean)
test['geo_mean'] = test['geohash'].map(geo_mean)

# fill missing (safety)
train['geo_mean'] = train['geo_mean'].fillna(train['demand'].mean())
test['geo_mean'] = test['geo_mean'].fillna(train['demand'].mean())

In [14]:
#adding it to the feature list
features = [
    'hour', 'minute', 'time_block',
    'lat', 'lon',
    'RoadType', 'Weather', 'LargeVehicles', 'Landmarks',
    'NumberofLanes',
    'Temperature',
    'lag_1',
    'geo_mean'
]

In [15]:
#Retrain model
model.fit(X_tr, y_tr)

preds = model.predict(X_val)

print("NEW R2 Score:", r2_score(y_val, preds))

NEW R2 Score: 0.741424268495842

In [1]:
import pandas as pd 
import numpy as np

In [2]:
train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")

In [3]:
#Basic team features
train[['hour','minute']] = train['timestamp'].str.split(':', expand=True).astype(int)
test[['hour','minute']] = test['timestamp'].str.split(':', expand=True).astype(int)

train['time_block'] = train['hour'] * 4 + train['minute'] // 15
test['time_block'] = test['hour'] * 4 + test['minute'] // 15

In [4]:
#cyclical encoding
train['hour_sin'] = np.sin(2*np.pi*train['hour']/24)
train['hour_cos'] = np.cos(2*np.pi*train['hour']/24)

test['hour_sin'] = np.sin(2*np.pi*test['hour']/24)
test['hour_cos'] = np.cos(2*np.pi*test['hour']/24)

In [5]:
#Categorical fix
from sklearn.preprocessing import LabelEncoder

for col in ['RoadType','Weather','LargeVehicles','Landmarks']:
    le = LabelEncoder()
    
    train[col] = train[col].astype(str)
    test[col] = test[col].astype(str)
    
    train[col] = le.fit_transform(train[col])
    
    # handle unseen in test
    test[col] = test[col].map(lambda x: le.transform([x])[0] if x in le.classes_ else -1)

In [6]:
#Feature list
features = [
    'hour','minute','time_block',
    'hour_sin','hour_cos',
    'RoadType','Weather','LargeVehicles','Landmarks'
]

In [7]:
#Train model
import xgboost as xgb
from sklearn.metrics import r2_score

X_train = train[train['day']==48][features]
y_train = train[train['day']==48]['demand']

X_val = train[train['day']==49][features]
y_val = train[train['day']==49]['demand']

model = xgb.XGBRegressor(
    n_estimators=800,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

model.fit(X_train, y_train)

pred = model.predict(X_val)

print("R2:", r2_score(y_val, pred))

R2: 0.7164734745029031

In [8]:
#Geo feature, location signal
geo_stats = train[train['day'] == 48].groupby('geohash')['demand'].mean()

train['geo_mean'] = train['geohash'].map(geo_stats)
test['geo_mean'] = test['geohash'].map(geo_stats)

# fill unseen
global_mean = train['demand'].mean()
train['geo_mean'] = train['geo_mean'].fillna(global_mean)
test['geo_mean'] = test['geo_mean'].fillna(global_mean)

In [9]:
geo_hour = train[train['day']==48].groupby(['geohash','hour'])['demand'].mean().reset_index()
geo_hour.columns = ['geohash','hour','geo_hour_mean']

train = train.merge(geo_hour, on=['geohash','hour'], how='left')
test = test.merge(geo_hour, on=['geohash','hour'], how='left')

train['geo_hour_mean'] = train['geo_hour_mean'].fillna(train['geo_mean'])
test['geo_hour_mean'] = test['geo_hour_mean'].fillna(test['geo_mean'])

In [10]:
features = [
    'hour','minute','time_block',
    'hour_sin','hour_cos',

    'RoadType','Weather','LargeVehicles','Landmarks',

    'geo_mean',
    'geo_hour_mean'
]

In [11]:
import xgboost as xgb
from sklearn.metrics import r2_score

X_train = train[train['day']==48][features]
y_train = train[train['day']==48]['demand']

X_val = train[train['day']==49][features]
y_val = train[train['day']==49]['demand']

model = xgb.XGBRegressor(
    n_estimators=800,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

model.fit(X_train, y_train)

pred = model.predict(X_val)

print("R2:", r2_score(y_val, pred))

R2: 0.7251125252208771

In [12]:
# LAG Feature 

day48 = train[train['day'] == 48][['geohash','hour','minute','demand']].copy()

day48 = day48.rename(columns={'demand':'lag_demand'})

# merge into train and test
train = train.merge(day48, on=['geohash','hour','minute'], how='left')
test  = test.merge(day48, on=['geohash','hour','minute'], how='left')

# fill missing safely
train['lag_demand'] = train['lag_demand'].fillna(train['geo_mean'])
test['lag_demand']  = test['lag_demand'].fillna(test['geo_mean'])

In [13]:
features = [
    'hour','minute','time_block',
    'hour_sin','hour_cos',

    'RoadType','Weather','LargeVehicles','Landmarks',

    'geo_mean',
    'geo_hour_mean',

    'lag_demand'   
]

In [14]:
import xgboost as xgb
from sklearn.metrics import r2_score

X_train = train[train['day']==48][features]
y_train = train[train['day']==48]['demand']

X_val = train[train['day']==49][features]
y_val = train[train['day']==49]['demand']

model = xgb.XGBRegressor(
    n_estimators=800,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

model.fit(X_train, y_train)

pred = model.predict(X_val)

print("R2:", r2_score(y_val, pred))

R2: 0.5835826677770833

In [15]:
day48 = train[train['day'] == 48][['geohash','timestamp','demand']].copy()
day48 = day48.rename(columns={'demand':'lag_demand'})

In [16]:
train = train.merge(day48, on=['geohash','timestamp'], how='left')
test  = test.merge(day48, on=['geohash','timestamp'], how='left')

In [17]:
train['lag_demand'] = train['lag_demand'].fillna(train['geo_mean'])
test['lag_demand']  = test['lag_demand'].fillna(test['geo_mean'])

KeyError: 'lag_demand'

In [18]:
day48 = train[train['day'] == 48][['geohash','timestamp','demand']].copy()
day48 = day48.rename(columns={'demand':'lag_demand'})

In [19]:
train = train.merge(day48, on=['geohash','timestamp'], how='left')
test  = test.merge(day48, on=['geohash','timestamp'], how='left')

In [20]:
train['lag_demand'] = train['lag_demand'].fillna(train['geo_mean'])
test['lag_demand']  = test['lag_demand'].fillna(test['geo_mean'])

In [21]:
print("Train missing:", train['lag_demand'].isnull().sum())
print("Test missing:", test['lag_demand'].isnull().sum())

Train missing: 0
Test missing: 0

In [22]:
train['lag_x_hour'] = train['lag_demand'] * train['hour']
test['lag_x_hour']  = test['lag_demand'] * test['hour']

train['lag_x_geo'] = train['lag_demand'] * train['geo_mean']
test['lag_x_geo']  = test['lag_demand'] * test['geo_mean']

In [23]:
train['lag_diff'] = train['lag_demand'] - train['geo_mean']
test['lag_diff']  = test['lag_demand'] - test['geo_mean']

In [24]:
features = [
    'hour','minute','time_block',
    'hour_sin','hour_cos',

    'RoadType','Weather','LargeVehicles','Landmarks',

    'geo_mean',
    'geo_hour_mean',

    'lag_demand',
    'lag_x_hour',
    'lag_x_geo',
    'lag_diff'
]

In [25]:
X_cols = features

In [26]:
X_train = train[train['day'] == 48][X_cols]
y_train = train[train['day'] == 48]['demand']

X_val = train[train['day'] == 49][X_cols]
y_val = train[train['day'] == 49]['demand']

In [27]:
import xgboost as xgb
from sklearn.metrics import r2_score

model = xgb.XGBRegressor(
    n_estimators=800,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1
)

In [28]:
model.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=800,
             n_jobs=-1, num_parallel_tree=None, ...)

In [29]:
preds = model.predict(X_val)

In [30]:
from sklearn.metrics import r2_score

print("R2:", r2_score(y_val, preds))

R2: 0.5493718214212999

In [31]:
features = [
    'hour','minute','time_block',
    'hour_sin','hour_cos',

    'RoadType','Weather','LargeVehicles','Landmarks',

    'geo_mean',
    'geo_hour_mean',

    'lag_demand'
]

In [32]:
missing_train = [c for c in features if c not in train.columns]
missing_test  = [c for c in features if c not in test.columns]

print("Missing in train:", missing_train)
print("Missing in test:", missing_test)

Missing in train: []
Missing in test: []

In [33]:
import xgboost as xgb
from sklearn.metrics import r2_score

X_train = train[train['day']==48][features]
y_train = train[train['day']==48]['demand']

X_val = train[train['day']==49][features]
y_val = train[train['day']==49]['demand']

model = xgb.XGBRegressor(
    n_estimators=800,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1
)

model.fit(X_train, y_train)

preds = model.predict(X_val)

print("R2:", r2_score(y_val, preds))

R2: 0.5835826677770833

In [1]:
import pandas as pd
import numpy as np

train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")

In [2]:
train[['hour','minute']] = train['timestamp'].str.split(':', expand=True).astype(int)
test[['hour','minute']] = test['timestamp'].str.split(':', expand=True).astype(int)

train['time_block'] = train['hour']*4 + train['minute']//15
test['time_block'] = test['hour']*4 + test['minute']//15

train['hour_sin'] = np.sin(2*np.pi*train['hour']/24)
train['hour_cos'] = np.cos(2*np.pi*train['hour']/24)

test['hour_sin'] = np.sin(2*np.pi*test['hour']/24)
test['hour_cos'] = np.cos(2*np.pi*test['hour']/24)

In [3]:
from sklearn.preprocessing import LabelEncoder

for col in ['RoadType','Weather','LargeVehicles','Landmarks']:
    le = LabelEncoder()
    
    train[col] = train[col].astype(str)
    test[col] = test[col].astype(str)
    
    train[col] = le.fit_transform(train[col])
    test[col] = test[col].apply(lambda x: x if x in le.classes_ else 'unknown')
    test[col] = le.transform(test[col])

In [4]:
features = [
    'hour','minute','time_block',
    'hour_sin','hour_cos',
    'RoadType','Weather','LargeVehicles','Landmarks'
]

In [5]:
import xgboost as xgb
from sklearn.metrics import r2_score

X_train = train[train['day']==48][features]
y_train = train[train['day']==48]['demand']

X_val = train[train['day']==49][features]
y_val = train[train['day']==49]['demand']

model = xgb.XGBRegressor(
    n_estimators=800,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

model.fit(X_train, y_train)

pred = model.predict(X_val)

print("R2:", r2_score(y_val, pred))

R2: 0.7164734745029031

In [6]:
from sklearn.preprocessing import LabelEncoder

for col in ['RoadType','Weather','LargeVehicles','Landmarks']:
    le = LabelEncoder()
    train[col] = le.fit_transform(train[col].astype(str))
    test[col] = le.transform(test[col].astype(str))

In [7]:
from xgboost import XGBRegressor
from sklearn.metrics import r2_score

X_train = train[train['day']==48][FEATURES]
y_train = train[train['day']==48]['demand']

X_val = train[train['day']==49][FEATURES]
y_val = train[train['day']==49]['demand']

model = XGBRegressor(
    n_estimators=500,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

model.fit(X_train, y_train)

pred = model.predict(X_val)

print("R2:", r2_score(y_val, pred))

NameError: name 'FEATURES' is not defined

In [8]:
import xgboost as xgb
from sklearn.metrics import r2_score

X_train = train[train['day']==48][features]
y_train = train[train['day']==48]['demand']

X_val = train[train['day']==49][features]
y_val = train[train['day']==49]['demand']

model = xgb.XGBRegressor(
    n_estimators=800,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

model.fit(X_train, y_train)

pred = model.predict(X_val)

print("R2:", r2_score(y_val, pred))

R2: 0.7164734745029031

In [9]:
print(train.columns.tolist())

['Index', 'geohash', 'day', 'timestamp', 'demand', 'RoadType', 'NumberofLanes', 'LargeVehicles', 'Landmarks', 'Temperature', 'Weather', 'hour', 'minute', 'time_block', 'hour_sin', 'hour_cos']

In [10]:
print(train[['geohash']].head())

  geohash
0  qp02z1
1  qp02zt
2  qp08bj
3  qp08gt
4  qp02zq

In [11]:
pip install pygeohash

Requirement already satisfied: pygeohash in C:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\site-packages (3.3.0)
Note: you may need to restart the kernel to use updated packages.

In [12]:
'geo_mean' in train.columns

False

In [13]:
# Creating geo mean
day48 = train[train['day'] == 48]

geo_mean = (
    day48.groupby('geohash')['demand']
    .mean()
    .reset_index()
)

geo_mean.columns = ['geohash', 'geo_mean']

train = train.merge(geo_mean, on='geohash', how='left')
test = test.merge(geo_mean, on='geohash', how='left')

global_mean = train['demand'].mean()

train['geo_mean'] = train['geo_mean'].fillna(global_mean)
test['geo_mean'] = test['geo_mean'].fillna(global_mean)

print(train[['geohash','geo_mean']].head())

  geohash  geo_mean
0  qp02z1  0.038898
1  qp02zt  0.218644
2  qp08bj  0.134725
3  qp08gt  0.014786
4  qp02zq  0.028176

In [14]:
print('geo_mean' in train.columns)
print(train['geo_mean'].describe())

True
count    77299.000000
mean         0.091709
std          0.117633
min          0.000360
25%          0.027039
50%          0.053560
75%          0.103480
max          0.957152
Name: geo_mean, dtype: float64

In [15]:
features = [
    'hour',
    'minute',
    'time_block',
    'hour_sin',
    'hour_cos',
    'NumberofLanes',
    'Temperature',
    'RoadType',
    'Weather',
    'LargeVehicles',
    'Landmarks',
    'geo_mean'
]

In [16]:
X_train = train[train['day']==48][features]
y_train = train[train['day']==48]['demand']

X_val = train[train['day']==49][features]
y_val = train[train['day']==49]['demand']

model.fit(X_train, y_train)

preds = model.predict(X_val)

from sklearn.metrics import r2_score
print("R2:", r2_score(y_val, preds))

R2: 0.7480806593248157

In [18]:
# geo-hour mean 
day48 = train[train['day'] == 48]

geo_hour = (
    day48.groupby(['geohash', 'hour'])['demand']
    .mean()
    .reset_index()
)

geo_hour.columns = ['geohash', 'hour', 'geo_hour_mean']

train = train.merge(
    geo_hour,
    on=['geohash', 'hour'],
    how='left'
)

test = test.merge(
    geo_hour,
    on=['geohash', 'hour'],
    how='left'
)

train['geo_hour_mean'] = train['geo_hour_mean'].fillna(train['geo_mean'])
test['geo_hour_mean'] = test['geo_hour_mean'].fillna(test['geo_mean'])

print(train[['geo_mean','geo_hour_mean']].head())

   geo_mean  geo_hour_mean
0  0.038898       0.033069
1  0.218644       0.168633
2  0.134725       0.060806
3  0.014786       0.013824
4  0.028176       0.020746

In [19]:
features = [
    'hour',
    'minute',
    'time_block',
    'hour_sin',
    'hour_cos',
    'NumberofLanes',
    'Temperature',
    'RoadType',
    'Weather',
    'LargeVehicles',
    'Landmarks',
    'geo_mean',
    'geo_hour_mean'
]

In [20]:
X_train = train[train['day']==48][features]
y_train = train[train['day']==48]['demand']

X_val = train[train['day']==49][features]
y_val = train[train['day']==49]['demand']

model.fit(X_train, y_train)

preds = model.predict(X_val)

from sklearn.metrics import r2_score
print("R2:", r2_score(y_val, preds))

R2: 0.7146809899466301

In [21]:
print(features)

['hour', 'minute', 'time_block', 'hour_sin', 'hour_cos', 'NumberofLanes', 'Temperature', 'RoadType', 'Weather', 'LargeVehicles', 'Landmarks', 'geo_mean', 'geo_hour_mean']

In [22]:
train.columns.tolist()

['Index',
 'geohash',
 'day',
 'timestamp',
 'demand',
 'RoadType',
 'NumberofLanes',
 'LargeVehicles',
 'Landmarks',
 'Temperature',
 'Weather',
 'hour',
 'minute',
 'time_block',
 'hour_sin',
 'hour_cos',
 'geo_mean',
 'geo_hour_mean']

In [23]:
print(features)

['hour', 'minute', 'time_block', 'hour_sin', 'hour_cos', 'NumberofLanes', 'Temperature', 'RoadType', 'Weather', 'LargeVehicles', 'Landmarks', 'geo_mean', 'geo_hour_mean']

In [24]:
print(train[['geo_mean','geo_hour_mean']].head())

print("\nMissing values:")
print(train[['geo_mean','geo_hour_mean']].isnull().sum())

print("\nStatistics:")
print(train[['geo_mean','geo_hour_mean']].describe())

   geo_mean  geo_hour_mean
0  0.038898       0.033069
1  0.218644       0.168633
2  0.134725       0.060806
3  0.014786       0.013824
4  0.028176       0.020746

Missing values:
geo_mean         0
geo_hour_mean    0
dtype: int64

Statistics:
           geo_mean  geo_hour_mean
count  77299.000000   77299.000000
mean       0.091709       0.089650
std        0.117633       0.135782
min        0.000360       0.000004
25%        0.027039       0.019568
50%        0.053560       0.045949
75%        0.103480       0.101870
max        0.957152       1.000000

In [25]:
corr1 = train['demand'].corr(train['geo_mean'])
corr2 = train['demand'].corr(train['geo_hour_mean'])

print("geo_mean correlation:", corr1)
print("geo_hour_mean correlation:", corr2)

geo_mean correlation: 0.8317164365331817
geo_hour_mean correlation: 0.9627377048065379

In [26]:
print(train[['geohash','hour','geo_hour_mean']].head())

print(
    train.groupby(['geohash','hour'])['geo_hour_mean']
         .nunique()
         .max()
)

  geohash  hour  geo_hour_mean
0  qp02z1     0       0.033069
1  qp02zt     0       0.168633
2  qp08bj     0       0.060806
3  qp08gt     0       0.013824
4  qp02zq     0       0.020746
1

In [27]:
X_train.dtypes

hour               int32
minute             int32
time_block         int32
hour_sin         float64
hour_cos         float64
NumberofLanes      int64
Temperature      float64
RoadType           int32
Weather            int32
LargeVehicles      int32
Landmarks          int32
geo_mean         float64
geo_hour_mean    float64
dtype: object

In [28]:
print(train[['geo_mean','geo_hour_mean','demand']].corr())

               geo_mean  geo_hour_mean    demand
geo_mean       1.000000       0.843410  0.831716
geo_hour_mean  0.843410       1.000000  0.962738
demand         0.831716       0.962738  1.000000

In [29]:
print(train[['geo_mean','geo_hour_mean']].describe())

           geo_mean  geo_hour_mean
count  77299.000000   77299.000000
mean       0.091709       0.089650
std        0.117633       0.135782
min        0.000360       0.000004
25%        0.027039       0.019568
50%        0.053560       0.045949
75%        0.103480       0.101870
max        0.957152       1.000000

In [30]:
print(train[['geo_mean','geo_hour_mean']].head(20))

    geo_mean  geo_hour_mean
0   0.038898       0.033069
1   0.218644       0.168633
2   0.134725       0.060806
3   0.014786       0.013824
4   0.028176       0.020746
5   0.528800       0.045217
6   0.143228       0.083243
7   0.139610       0.023790
8   0.042644       0.013036
9   0.017057       0.004520
10  0.101505       0.047718
11  0.163650       0.042758
12  0.332827       0.059956
13  0.335459       0.255261
14  0.071875       0.039754
15  0.024927       0.005091
16  0.112991       0.015838
17  0.148670       0.029627
18  0.007853       0.006316
19  0.020512       0.009882

In [31]:
day48 = train[train['day'] == 48]

print(
    day48[['geo_hour_mean','demand']].corr()
)

               geo_hour_mean    demand
geo_hour_mean       1.000000  0.985406
demand              0.985406  1.000000

In [32]:
day49 = train[train['day'] == 49]

print(
    day49[['geo_hour_mean','demand']].corr()
)

               geo_hour_mean    demand
geo_hour_mean       1.000000  0.817645
demand              0.817645  1.000000

In [33]:
day48 = train[train['day']==48]

geo_hour = day48.groupby(
    ['geohash','hour']
)['demand'].mean()

In [35]:
geo_hour_counts = train[train['day']==48].groupby(
    ['geohash','hour']
).size()

print(geo_hour_counts.describe())

count    20806.000000
mean         3.336874
std          1.057397
min          1.000000
25%          3.000000
50%          4.000000
75%          4.000000
max          4.000000
dtype: float64

In [36]:
print(train.columns.tolist())

['Index', 'geohash', 'day', 'timestamp', 'demand', 'RoadType', 'NumberofLanes', 'LargeVehicles', 'Landmarks', 'Temperature', 'Weather', 'hour', 'minute', 'time_block', 'hour_sin', 'hour_cos', 'geo_mean', 'geo_hour_mean']

In [38]:
train.columns.tolist()

['Index',
 'geohash',
 'day',
 'timestamp',
 'demand',
 'RoadType',
 'NumberofLanes',
 'LargeVehicles',
 'Landmarks',
 'Temperature',
 'Weather',
 'hour',
 'minute',
 'time_block',
 'hour_sin',
 'hour_cos',
 'geo_mean',
 'geo_hour_mean']

In [39]:
train[['geohash','hour','geo_mean','geo_hour_mean','demand']].sample(20)

      geohash  hour  geo_mean  geo_hour_mean    demand
66830  qp09ep    23  0.028585       0.045890  0.027725
40076  qp03xw    11  0.380147       0.492324  0.539877
6522   qp03rs     2  0.025950       0.020575  0.017842
27529  qp09dg     7  0.109221       0.176689  0.204203
15232  qp08c5     4  0.029556       0.068917  0.039527
42091  qp0d03    11  0.007391       0.009264  0.008396
71755  qp09g1     0  0.080446       0.067611  0.124321
4786   qp03qk     1  0.014167       0.000306  0.000306
9654   qp09cn     2  0.018827       0.030636  0.005044
20413  qp09f8     5  0.009720       0.004017  0.003597
40658  qp03r5    11  0.062994       0.059457  0.074332
45279  qp03tg    12  0.018210       0.008482  0.002266
54300  qp09ss    15  0.063879       0.060142  0.026001
36279  qp0992    10  0.097879       0.094426  0.065091
31295  qp09gw     8  0.063024       0.095742  0.095184
38576  qp0d0j    10  0.028180       0.023703  0.000537
38743  qp09hv    11  0.055781       0.086737  0.080929
32558  qp09m9     9  0.017989       0.017344  0.025619
64612  qp03q5    22  0.052360       0.097726  0.083886
4402   qp03zq     1  0.004389       0.005620  0.005620

In [40]:
day49 = train[train['day']==49]

print(day49[['geo_mean','geo_hour_mean','demand']].corr())

               geo_mean  geo_hour_mean    demand
geo_mean       1.000000       0.869249  0.825863
geo_hour_mean  0.869249       1.000000  0.817645
demand         0.825863       0.817645  1.000000

In [41]:
train[train['day']==48].shape

(69427, 18)

In [42]:
train[train['day']==49].shape

(7872, 18)

In [43]:
train[['geohash','timestamp']].duplicated().sum()

6423

In [44]:
train.groupby(['geohash','timestamp']).size().describe()

count    70876.000000
mean         1.090623
std          0.287074
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          2.000000
dtype: float64

In [45]:
train.groupby(['geohash','timestamp'])['demand'].agg(['mean','std']).head()

                       mean  std
geohash timestamp
qp02yc  10:30      0.046790  NaN
        10:45      0.021158  NaN
        1:0        0.005397  NaN
        2:30       0.012944  NaN
        2:45       0.025961  NaN

In [46]:
day48_lookup = (
    train[train['day']==48]
    .groupby(['geohash','timestamp'])['demand']
    .mean()
    .reset_index()
)

print(day48_lookup.shape)

(69427, 3)

In [47]:
day49 = train[train['day']==49].copy()

day49 = day49.merge(
    day48_lookup,
    on=['geohash','timestamp'],
    how='left',
    suffixes=('','_lag')
)

print(day49['demand_lag'].isna().sum())
print(len(day49))

1449
7872

In [48]:
print(
    day49[['demand', 'demand_lag']]
    .corr()
)

              demand  demand_lag
demand      1.000000    0.792394
demand_lag  0.792394    1.000000

In [49]:
day48_lookup = (
    train[train['day']==48]
    .groupby(['geohash','timestamp'])['demand']
    .mean()
    .reset_index()
)

day48_lookup.rename(
    columns={'demand':'lag_demand'},
    inplace=True
)

In [50]:
train = train.merge(
    day48_lookup,
    on=['geohash','timestamp'],
    how='left'
)

test = test.merge(
    day48_lookup,
    on=['geohash','timestamp'],
    how='left'
)

In [51]:
print(train['lag_demand'].isna().sum())
print(test['lag_demand'].isna().sum())

1449
4642

In [52]:
train['lag_missing'] = train['lag_demand'].isna().astype(int)
test['lag_missing'] = test['lag_demand'].isna().astype(int)

print(train['lag_missing'].value_counts())
print(test['lag_missing'].value_counts())

lag_missing
0    75850
1     1449
Name: count, dtype: int64
lag_missing
0    37136
1     4642
Name: count, dtype: int64

In [53]:
train['lag_demand'] = train['lag_demand'].fillna(train['geo_mean'])
test['lag_demand'] = test['lag_demand'].fillna(test['geo_mean'])

In [54]:
print(train['lag_demand'].isna().sum())
print(test['lag_demand'].isna().sum())

0
0

In [55]:
FEATURES = [
    'hour',
    'minute',
    'time_block',
    'hour_sin',
    'hour_cos',

    'NumberofLanes',
    'Temperature',

    'RoadType',
    'Weather',
    'LargeVehicles',
    'Landmarks',

    'geo_mean',

    'lag_demand',
    'lag_missing'
]

In [56]:
X_tr = train[train['day']==48][FEATURES]
y_tr = train[train['day']==48]['demand']

X_val = train[train['day']==49][FEATURES]
y_val = train[train['day']==49]['demand']

In [57]:
X_tr = train[train['day']==48][FEATURES]
y_tr = train[train['day']==48]['demand']

X_val = train[train['day']==49][FEATURES]
y_val = train[train['day']==49]['demand']

In [58]:
import xgboost as xgb
from sklearn.metrics import r2_score

model = xgb.XGBRegressor(
    n_estimators=500,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

model.fit(X_tr, y_tr)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=500,
             n_jobs=None, num_parallel_tree=None, ...)

In [59]:
preds = model.predict(X_val)

r2 = r2_score(y_val, preds)

print("R2:", r2)

R2: 0.5881557877454008

In [60]:
print(train[['lag_demand']].describe()

SyntaxError: incomplete input (237361957.py, line 1)

In [61]:
print(train[['lag_demand']].describe())

         lag_demand
count  7.729900e+04
mean   8.984401e-02
std    1.377580e-01
min    6.245650e-07
25%    1.758184e-02
50%    4.552718e-02
75%    1.034740e-01
max    1.000000e+00

In [62]:
print(train[['demand','lag_demand']].corr())

              demand  lag_demand
demand      1.000000    0.974897
lag_demand  0.974897    1.000000

In [63]:
print(train[['demand','lag_demand']].corr())

              demand  lag_demand
demand      1.000000    0.974897
lag_demand  0.974897    1.000000

In [64]:
print(
    train[['demand','lag_demand']]
    .sample(20, random_state=42)
)

         demand  lag_demand
65165  0.132365    0.132365
58878  0.088500    0.088500
6000   0.032429    0.032429
27540  0.027974    0.027974
70232  0.047485    0.018341
72393  0.043124    0.024406
74279  0.401779    0.133466
71876  0.060211    0.001979
630    0.109597    0.109597
652    0.004044    0.004044
52511  0.003108    0.003108
45887  0.083190    0.083190
31045  0.039830    0.039830
59780  0.129950    0.129950
28939  0.021232    0.021232
26394  0.037589    0.037589
13542  0.005005    0.005005
23313  0.093466    0.093466
45146  0.000929    0.000929
34464  0.083697    0.083697

In [65]:
print(train[train['day']==48'][['demand','lag_demand']].head(20))

SyntaxError: unterminated string literal (detected at line 1) (4238120150.py, line 1)

In [67]:
print(train[train['day'] == 48][['demand', 'lag_demand']].head(20))

      demand  lag_demand
0   0.048804    0.048804
1   0.118507    0.118507
2   0.027132    0.027132
3   0.003272    0.003272
4   0.010819    0.010819
5   0.016262    0.016262
6   0.042247    0.042247
7   0.040135    0.040135
8   0.001002    0.001002
9   0.003948    0.003948
10  0.017780    0.017780
11  0.089060    0.089060
12  0.050096    0.050096
13  0.152598    0.152598
14  0.011870    0.011870
15  0.005091    0.005091
16  0.001492    0.001492
17  0.003284    0.003284
18  0.001297    0.001297
19  0.003276    0.003276

In [68]:
print(
    (
        train[train['day'] == 48]['demand']
        ==
        train[train['day'] == 48]['lag_demand']
    ).mean()
)

1.0

In [69]:
print(train.columns.tolist())

['Index', 'geohash', 'day', 'timestamp', 'demand', 'RoadType', 'NumberofLanes', 'LargeVehicles', 'Landmarks', 'Temperature', 'Weather', 'hour', 'minute', 'time_block', 'hour_sin', 'hour_cos', 'geo_mean', 'geo_hour_mean', 'lag_demand', 'lag_missing']

In [70]:
importance = pd.DataFrame({
    'feature': best_features,
    'importance': model.feature_importances_
})

importance.sort_values(
    by='importance',
    ascending=False
)

NameError: name 'best_features' is not defined

In [71]:
best_features = [
    'hour',
    'minute',
    'time_block',
    'hour_sin',
    'hour_cos',
    'NumberofLanes',
    'Temperature',
    'RoadType',
    'Weather',
    'LargeVehicles',
    'Landmarks',
    'geo_mean'
]

In [72]:
import lightgbm as lgb

train_day48 = df[df['day'] == 48]
val_day49   = df[df['day'] == 49]

features = [
    'hour', 'minute', 'time_block', 'hour_sin', 'hour_cos',
    'NumberofLanes', 'Temperature', 'RoadType', 'Weather',
    'LargeVehicles', 'Landmarks', 'geo_mean'
]

X_train, y_train = train_day48[features], train_day48['demand']
X_val,   y_val   = val_day49[features],   val_day49['demand']

model = lgb.LGBMRegressor(
    objective='regression_l1',   # MAE — robust to your skewed demand
    n_estimators=3000,
    learning_rate=0.03,
    num_leaves=255,
    min_child_samples=20,
    feature_fraction=0.8,
    bagging_fraction=0.8,
    bagging_freq=1,
    reg_alpha=0.1,
    reg_lambda=0.1,
    random_state=42,
    n_jobs=-1
)

model.fit(
    X_train, y_train,
    eval_set=[(X_val, y_val)],
    callbacks=[lgb.early_stopping(100), lgb.log_evaluation(200)]
)

ModuleNotFoundError: No module named 'lightgbm'

In [73]:
best_features = [
    'hour',
    'minute',
    'time_block',
    'hour_sin',
    'hour_cos',
    'NumberofLanes',
    'Temperature',
    'RoadType',
    'Weather',
    'LargeVehicles',
    'Landmarks',
    'geo_mean'
]

importance = pd.DataFrame({
    "feature": best_features,
    "importance": model.feature_importances_
})

print(
    importance.sort_values(
        "importance",
        ascending=False
    )
)

ValueError: All arrays must be of the same length

In [74]:
print("Features:", len(best_features))
print("Importances:", len(model.feature_importances_))

Features: 12
Importances: 14

In [75]:
print(model.feature_importances_)

[1.7531104e-03 2.5656435e-04 2.3982839e-03 6.3193273e-03 2.9196134e-03
 2.3259623e-03 3.8772594e-04 3.7225458e-01 3.6182316e-04 1.6338579e-01
 7.8843051e-04 3.2326475e-02 4.1452238e-01 0.0000000e+00]

In [1]:
import pandas as pd
import numpy as np
import pygeohash as pgh
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import r2_score
import lightgbm as lgb
import warnings
warnings.filterwarnings('ignore')

train = pd.read_csv("train.csv")
test  = pd.read_csv("test.csv")

# Missing value fills
train['Temperature'] = train['Temperature'].fillna(train['Temperature'].median())
test['Temperature']  = test['Temperature'].fillna(train['Temperature'].median())

weather_mode = train['Weather'].mode()[0]
train['Weather'] = train['Weather'].fillna(weather_mode)
test['Weather']  = test['Weather'].fillna(weather_mode)

train['RoadType'] = train['RoadType'].fillna('Unknown')
test['RoadType']  = test['RoadType'].fillna('Unknown')

for col in ['LargeVehicles', 'Landmarks']:
    m = train[col].mode()[0]
    train[col] = train[col].fillna(m)
    test[col]  = test[col].fillna(m)

ModuleNotFoundError: No module named 'lightgbm'

In [ ]:
for df in [train, test]:
    df['hour']       = df['timestamp'].apply(lambda x: int(x.split(':')[0]))
    df['minute']     = df['timestamp'].apply(lambda x: int(x.split(':')[1]))
    df['time_block'] = df['hour'] * 4 + df['minute'] // 15
    df['hour_sin']   = np.sin(2 * np.pi * df['hour'] / 24)
    df['hour_cos']   = np.cos(2 * np.pi * df['hour'] / 24)
    df['is_morning_peak'] = df['hour'].isin([7,8,9]).astype(int)
    df['is_evening_peak'] = df['hour'].isin([17,18,19]).astype(int)
    df['is_night']        = df['hour'].isin([0,1,2,3,4,5]).astype(int)

In [1]:
!pip install lightgbm

Collecting lightgbm
  Downloading lightgbm-4.6.0-py3-none-win_amd64.whl.metadata (17 kB)
Requirement already satisfied: numpy>=1.17.0 in C:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\site-packages (from lightgbm) (1.26.4)
Requirement already satisfied: scipy in C:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\site-packages (from lightgbm) (1.17.1)
Downloading lightgbm-4.6.0-py3-none-win_amd64.whl (1.5 MB)
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   --------------------- ------------------ 0.8/1.5 MB 5.6 MB/s eta 0:00:01
   ---------------------------------------- 1.5/1.5 MB 5.1 MB/s  0:00:00
Installing collected packages: lightgbm
Successfully installed lightgbm-4.6.0

In [2]:
pip install pygeohash

Requirement already satisfied: pygeohash in C:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\site-packages (3.3.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd
import numpy as np
import pygeohash as pgh
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import r2_score
import lightgbm as lgb
import warnings
warnings.filterwarnings('ignore')

train = pd.read_csv("train.csv")
test  = pd.read_csv("test.csv")

# Missing value fills
train['Temperature'] = train['Temperature'].fillna(train['Temperature'].median())
test['Temperature']  = test['Temperature'].fillna(train['Temperature'].median())

weather_mode = train['Weather'].mode()[0]
train['Weather'] = train['Weather'].fillna(weather_mode)
test['Weather']  = test['Weather'].fillna(weather_mode)

train['RoadType'] = train['RoadType'].fillna('Unknown')
test['RoadType']  = test['RoadType'].fillna('Unknown')

for col in ['LargeVehicles', 'Landmarks']:
    m = train[col].mode()[0]
    train[col] = train[col].fillna(m)
    test[col]  = test[col].fillna(m)

In [4]:
for df in [train, test]:
    df['hour']       = df['timestamp'].apply(lambda x: int(x.split(':')[0]))
    df['minute']     = df['timestamp'].apply(lambda x: int(x.split(':')[1]))
    df['time_block'] = df['hour'] * 4 + df['minute'] // 15
    df['hour_sin']   = np.sin(2 * np.pi * df['hour'] / 24)
    df['hour_cos']   = np.cos(2 * np.pi * df['hour'] / 24)
    df['is_morning_peak'] = df['hour'].isin([7,8,9]).astype(int)
    df['is_evening_peak'] = df['hour'].isin([17,18,19]).astype(int)
    df['is_night']        = df['hour'].isin([0,1,2,3,4,5]).astype(int)

In [5]:
def decode_gh(gh):
    lat, lon = pgh.decode(gh)
    return float(lat), float(lon)

for df in [train, test]:
    coords = df['geohash'].apply(decode_gh)
    df['lat'] = coords.apply(lambda x: x[0])
    df['lon'] = coords.apply(lambda x: x[1])
    df['geo4'] = df['geohash'].str[:4]
    df['geo3'] = df['geohash'].str[:3]

In [6]:
# Compute ALL stats on train only
global_mean = train['demand'].mean()

def smoothed_mean(df_train, df_target, group_cols, alpha=10):
    stats = df_train.groupby(group_cols)['demand'].agg(['mean','count'])
    stats['sm'] = (stats['mean']*stats['count'] + global_mean*alpha) / (stats['count']+alpha)
    key = '_'.join(group_cols) + '_mean'
    return stats['sm'].rename(key), key

# geo_mean (geohash level)
geo_sm, _ = smoothed_mean(train, train, ['geohash'])
for df in [train, test]:
    df['geo_mean'] = df['geohash'].map(geo_sm).fillna(global_mean)

# geo4_mean (neighbourhood level)
geo4_sm, _ = smoothed_mean(train, train, ['geo4'])
for df in [train, test]:
    df['geo4_mean'] = df['geo4'].map(geo4_sm).fillna(global_mean)

# geo3_mean (zone level)
geo3_sm, _ = smoothed_mean(train, train, ['geo3'])
for df in [train, test]:
    df['geo3_mean'] = df['geo3'].map(geo3_sm).fillna(global_mean)

# geo_hour_mean — SMOOTHED (this is what was killing you before)
geo_hour_stats = train.groupby(['geohash','hour'])['demand'].agg(['mean','count'])
geo_hour_stats['sm'] = (
    (geo_hour_stats['mean']*geo_hour_stats['count'] + global_mean*10)
    / (geo_hour_stats['count']+10)
)
for df in [train, test]:
    df['geo_hour_mean'] = df.set_index(['geohash','hour']).index.map(
        geo_hour_stats['sm']
    ).fillna(global_mean).values

In [7]:
# Build lookup from day 48 only
lag_lookup = (
    train[train['day']==48]
    .groupby(['geohash','timestamp'])['demand']
    .mean()
    .reset_index()
    .rename(columns={'demand':'lag_demand'})
)

# Day 48 train rows: use geo_mean as lag (no day 47 data)
train['lag_demand'] = train['geo_mean'].copy()
train['lag_missing'] = 0

# Day 49 val rows: merge actual day48 demand
day49_idx = train['day'] == 49
day49_with_lag = train[day49_idx].drop(columns=['lag_demand','lag_missing']).merge(
    lag_lookup, on=['geohash','timestamp'], how='left'
)
day49_with_lag['lag_missing'] = day49_with_lag['lag_demand'].isna().astype(int)
day49_with_lag['lag_demand'] = day49_with_lag['lag_demand'].fillna(
    day49_with_lag['geo_mean']
)
train.loc[day49_idx, 'lag_demand'] = day49_with_lag['lag_demand'].values
train.loc[day49_idx, 'lag_missing'] = day49_with_lag['lag_missing'].values

# Test rows
test = test.merge(lag_lookup, on=['geohash','timestamp'], how='left')
test['lag_missing'] = test['lag_demand'].isna().astype(int)
test['lag_demand'] = test['lag_demand'].fillna(test['geo_mean'])

# Ratio feature
for df in [train, test]:
    df['lag_ratio'] = df['lag_demand'] / (df['geo_mean'] + 1e-5)

In [8]:
cat_cols = ['RoadType', 'Weather', 'LargeVehicles', 'Landmarks']
for col in cat_cols:
    le = LabelEncoder()
    combined = pd.concat([train[col], test[col]]).astype(str)
    le.fit(combined)
    train[col] = le.transform(train[col].astype(str))
    test[col]  = le.transform(test[col].astype(str))

In [9]:
FEATURES = [
    'hour', 'minute', 'time_block', 'hour_sin', 'hour_cos',
    'is_morning_peak', 'is_evening_peak', 'is_night',
    'lat', 'lon',
    'NumberofLanes', 'Temperature',
    'RoadType', 'Weather', 'LargeVehicles', 'Landmarks',
    'geo_mean', 'geo4_mean', 'geo3_mean', 'geo_hour_mean',
    'lag_demand', 'lag_missing', 'lag_ratio'
]

X_tr  = train[train['day']==48][FEATURES]
y_tr  = train[train['day']==48]['demand']
X_val = train[train['day']==49][FEATURES]
y_val = train[train['day']==49]['demand']

model = lgb.LGBMRegressor(
    objective='regression_l1',
    n_estimators=3000,
    learning_rate=0.03,
    num_leaves=255,
    min_child_samples=20,
    feature_fraction=0.8,
    bagging_fraction=0.8,
    bagging_freq=1,
    reg_alpha=0.1,
    reg_lambda=0.1,
    random_state=42,
    n_jobs=-1
)

model.fit(
    X_tr, y_tr,
    eval_set=[(X_val, y_val)],
    callbacks=[lgb.early_stopping(100), lgb.log_evaluation(200)]
)

preds = model.predict(X_val)
print("DAY-BASED R²:", r2_score(y_val, preds))

[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=1, subsample_freq=0 will be ignored. Current value: bagging_freq=1
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=1, subsample_freq=0 will be ignored. Current value: bagging_freq=1
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.017661 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1553
[LightGBM] [Info] Number of data points in the train set: 69427, number of used features: 21
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=1, subsample_freq=0 will be ignored. Current value: bagging_freq=1
[LightGBM] [Info] Start training from score 0.046806
Training until validation scores don't improve for 100 rounds
[200]	valid_0's l1: 0.043629
Early stopping, best iteration is:
[281]	valid_0's l1: 0.0435438
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=1, subsample_freq=0 will be ignored. Current value: bagging_freq=1
DAY-BASED R²: 0.7181703989754121

In [10]:
print(len(features))
print(len(model.feature_importances_))

NameError: name 'features' is not defined

In [11]:
print(type(model))

<class 'lightgbm.sklearn.LGBMRegressor'>

In [12]:
print(len(model.feature_importances_))

23

In [13]:
importance = pd.DataFrame({
    'feature': FEATURES,
    'importance': model.feature_importances_
})

importance = importance.sort_values(
    by='importance',
    ascending=False
)

print(importance)

            feature  importance
16         geo_mean       12358
19    geo_hour_mean       10590
11      Temperature        8740
9               lon        7854
2        time_block        7618
8               lat        7173
0              hour        3358
3          hour_sin        2740
1            minute        2689
20       lag_demand        1972
4          hour_cos        1550
10    NumberofLanes        1545
13          Weather        1173
17        geo4_mean         986
12         RoadType         519
15        Landmarks         167
14    LargeVehicles         137
5   is_morning_peak          86
6   is_evening_peak          64
22        lag_ratio          44
7          is_night          11
18        geo3_mean           0
21      lag_missing           0

In [14]:
features = [
    'hour',
    'minute',
    'time_block',
    'hour_sin',
    'hour_cos',
    'NumberofLanes',
    'Temperature',
    'RoadType',
    'Weather',
    'LargeVehicles',
    'Landmarks',
    'geo_mean',
    'lat',
    'lon'
]

In [15]:
print(train[['lat', 'lon', 'geo_mean']].head())

        lat        lon  geo_mean
0 -5.484924  90.664673  0.052581
1 -5.462952  90.686646  0.197168
2 -5.462952  90.708618  0.123517
3 -5.462952  90.862427  0.029681
4 -5.457458  90.675659  0.043352

In [16]:
FEATURES = [
    'hour',
    'minute',
    'time_block',
    'hour_sin',
    'hour_cos',
    'NumberofLanes',
    'Temperature',
    'RoadType',
    'Weather',
    'LargeVehicles',
    'Landmarks',
    'geo_mean',
    'lat',
    'lon'
]

In [17]:
X_tr = train[train['day'] == 48][FEATURES]
y_tr = train[train['day'] == 48]['demand']

X_val = train[train['day'] == 49][FEATURES]
y_val = train[train['day'] == 49]['demand']

In [18]:
from xgboost import XGBRegressor

model = XGBRegressor(
    n_estimators=500,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1
)

model.fit(X_tr, y_tr)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=500,
             n_jobs=-1, num_parallel_tree=None, ...)

In [19]:
from sklearn.metrics import r2_score

preds = model.predict(X_val)

r2 = r2_score(y_val, preds)

print("R2:", r2)

R2: 0.7483134852517266

In [20]:
FEATURES = [
    'hour','minute','time_block','hour_sin','hour_cos',
    'NumberofLanes','Temperature',
    'RoadType','Weather','LargeVehicles','Landmarks',
    'geo_mean','lat','lon'
]

In [21]:
from xgboost import XGBRegressor
from sklearn.metrics import r2_score

model = XGBRegressor(
    n_estimators=3000,
    learning_rate=0.03,
    max_depth=8,
    subsample=0.8,
    colsample_bytree=0.8,
    min_child_weight=3,
    gamma=0.1,
    reg_alpha=0.1,
    reg_lambda=1.0,
    tree_method='hist',
    random_state=42,
    n_jobs=-1
)

model.fit(
    X_tr, y_tr,
    eval_set=[(X_val, y_val)],
    verbose=200
)

preds = model.predict(X_val)
print("R2:", r2_score(y_val, preds))

[0]	validation_0-rmse:0.14220
[200]	validation_0-rmse:0.06586
[400]	validation_0-rmse:0.06585
[600]	validation_0-rmse:0.06586
[800]	validation_0-rmse:0.06589
[1000]	validation_0-rmse:0.06589
[1200]	validation_0-rmse:0.06589
[1400]	validation_0-rmse:0.06589
[1600]	validation_0-rmse:0.06590
[1800]	validation_0-rmse:0.06589
[2000]	validation_0-rmse:0.06593
[2200]	validation_0-rmse:0.06592
[2400]	validation_0-rmse:0.06593
[2600]	validation_0-rmse:0.06593
[2800]	validation_0-rmse:0.06593
[2999]	validation_0-rmse:0.06593
R2: 0.7926491117697854

In [22]:
print("Train R2:", r2_score(y_tr, model.predict(X_tr)))
print("Val R2:", r2_score(y_val, preds))

Train R2: 0.9412930856050609
Val R2: 0.7926491117697854

In [23]:
model = XGBRegressor(
    n_estimators=2000,          # reduce
    learning_rate=0.03,
    max_depth=6,                # IMPORTANT change
    subsample=0.7,             # more randomness
    colsample_bytree=0.7,
    min_child_weight=5,        # stronger regularization
    gamma=0.2,
    reg_alpha=0.3,
    reg_lambda=2.0,
    tree_method='hist',
    random_state=42,
    n_jobs=-1
)

model.fit(
    X_tr, y_tr,
    eval_set=[(X_val, y_val)],
    verbose=200
)

preds = model.predict(X_val)
print("R2:", r2_score(y_val, preds))

[0]	validation_0-rmse:0.14303
[200]	validation_0-rmse:0.06539
[400]	validation_0-rmse:0.06527
[600]	validation_0-rmse:0.06527
[800]	validation_0-rmse:0.06527
[1000]	validation_0-rmse:0.06527
[1200]	validation_0-rmse:0.06531
[1400]	validation_0-rmse:0.06531
[1600]	validation_0-rmse:0.06531
[1800]	validation_0-rmse:0.06529
[1999]	validation_0-rmse:0.06529
R2: 0.7966616287843193

In [24]:
final_train = train.copy()

In [25]:
from xgboost import XGBRegressor

model_final = XGBRegressor(
    n_estimators=3000,
    learning_rate=0.03,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    min_child_weight=5,
    gamma=0.2,
    reg_alpha=0.3,
    reg_lambda=2.0,
    tree_method='hist',
    random_state=42,
    n_jobs=-1
)

model_final.fit(final_train[FEATURES], final_train['demand'])

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=0.2, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.03, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
             max_leaves=None, min_child_weight=5, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=3000,
             n_jobs=-1, num_parallel_tree=None, ...)

In [26]:
test_preds = model_final.predict(test[FEATURES])

In [27]:
submission = pd.DataFrame({
    "Index": test["Index"],
    "demand": test_preds
})

In [28]:
print(submission.head())
print(submission["demand"].describe())

   Index    demand
0      0  0.045963
1      1  0.035268
2      2  0.082611
3      3  0.044318
4      4  0.054643
count    41778.000000
mean         0.120222
std          0.162006
min          0.017333
25%          0.028036
50%          0.056582
75%          0.123421
max          0.971248
Name: demand, dtype: float64

In [29]:
submission.to_csv("submission.csv", index=False)

PermissionError: [Errno 13] Permission denied: 'submission.csv'

In [30]:
train = train.sort_values(['geohash','day','time_block'])

train['lag_1'] = train.groupby('geohash')['demand'].shift(1)
train['lag_2'] = train.groupby('geohash')['demand'].shift(2)

train['rolling_mean_3'] = (
    train.groupby('geohash')['demand']
    .shift(1)
    .rolling(3)
    .mean()
    .reset_index(level=0, drop=True)
)

In [31]:
global_mean = train['demand'].mean()

stats = train.groupby(['geohash','hour'])['demand'].agg(['mean','count'])

stats['smooth'] = (
    stats['mean']*stats['count'] + global_mean*20
) / (stats['count'] + 20)

train = train.merge(stats['smooth'], on=['geohash','hour'], how='left')
test = test.merge(stats['smooth'], on=['geohash','hour'], how='left')

train['geo_hour_smooth'] = train['smooth'].fillna(global_mean)
test['geo_hour_smooth'] = test['smooth'].fillna(global_mean)

In [32]:
train = train.sort_values(['geohash','day','time_block'])

train['lag1'] = train.groupby('geohash')['demand'].shift(1)
train['lag2'] = train.groupby('geohash')['demand'].shift(2)

train['roll_mean_3'] = train.groupby('geohash')['demand'] \
    .transform(lambda x: x.shift(1).rolling(3).mean())

In [33]:
train['hour_mean_global'] = train.groupby('hour')['demand'].transform('mean')
test['hour_mean_global'] = test['hour'].map(train.groupby('hour')['demand'].mean())

In [34]:
train = train.sort_values(['geohash', 'day', 'time_block'])

train['lag_1'] = train.groupby('geohash')['demand'].shift(1)
train['lag_2'] = train.groupby('geohash')['demand'].shift(2)

train['roll_mean_3'] = (
    train.groupby('geohash')['demand']
    .transform(lambda x: x.shift(1).rolling(3).mean())
)

In [35]:
FEATURES = FEATURES + ['lag_1', 'lag_2', 'roll_mean_3']

In [36]:
FEATURES = [
    'hour', 'minute', 'time_block', 'hour_sin', 'hour_cos',
    'NumberofLanes', 'Temperature', 'RoadType', 'Weather',
    'LargeVehicles', 'Landmarks',
    'geo_mean', 'geo_hour_mean',
    'lag_1', 'lag_2', 'roll_mean_3'
]

In [37]:
from xgboost import XGBRegressor
from sklearn.metrics import r2_score

model = XGBRegressor(
    n_estimators=3000,
    learning_rate=0.03,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    min_child_weight=5,
    gamma=0.2,
    reg_alpha=0.3,
    reg_lambda=2.0,
    tree_method='hist',
    random_state=42,
    n_jobs=-1
)

model.fit(X_tr, y_tr)

preds = model.predict(X_val)

print("NEW R2:", r2_score(y_val, preds))

NEW R2: 0.798423618648748

In [38]:
import lightgbm as lgb

lgb_model = lgb.LGBMRegressor(
    n_estimators=3000,
    learning_rate=0.03,
    num_leaves=63,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

lgb_model.fit(X_tr, y_tr)

lgb_preds = lgb_model.predict(X_val)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.017894 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 775
[LightGBM] [Info] Number of data points in the train set: 69427, number of used features: 14
[LightGBM] [Info] Start training from score 0.092659

In [39]:
xgb_preds = model.predict(X_val)

final_preds = 0.7 * xgb_preds + 0.3 * lgb_preds

from sklearn.metrics import r2_score
print("ENSEMBLE R2:", r2_score(y_val, final_preds))

ENSEMBLE R2: 0.7892953274022448

In [40]:
global_mean = train['demand'].mean()

geo_hour_stats = train.groupby(['geohash','hour'])['demand'].agg(['mean','count'])

geo_hour_stats['smooth'] = (
    geo_hour_stats['mean'] * geo_hour_stats['count'] +
    global_mean * 30
) / (geo_hour_stats['count'] + 30)

train = train.merge(geo_hour_stats['smooth'], on=['geohash','hour'], how='left')
test = test.merge(geo_hour_stats['smooth'], on=['geohash','hour'], how='left')

train['geo_hour_smooth'] = train['smooth'].fillna(global_mean)
test['geo_hour_smooth'] = test['smooth'].fillna(global_mean)

KeyError: 'smooth'

In [41]:
global_mean = train['demand'].mean()

geo_hour_stats = train.groupby(['geohash','hour'])['demand'].agg(['mean','count'])

geo_hour_stats['smooth'] = (
    geo_hour_stats['mean'] * geo_hour_stats['count'] +
    global_mean * 30
) / (geo_hour_stats['count'] + 30)

geo_hour_stats = geo_hour_stats.reset_index()

In [42]:
train = train.merge(
    geo_hour_stats[['geohash','hour','smooth']],
    on=['geohash','hour'],
    how='left'
)

test = test.merge(
    geo_hour_stats[['geohash','hour','smooth']],
    on=['geohash','hour'],
    how='left'
)

In [43]:
train['geo_hour_smooth'] = train['smooth'].fillna(global_mean)
test['geo_hour_smooth'] = test['smooth'].fillna(global_mean)

In [44]:
train.drop(columns=['smooth'], inplace=True)
test.drop(columns=['smooth'], inplace=True)

In [45]:
global_mean = train['demand'].mean()

geo_hour_stats = train.groupby(['geohash','hour'])['demand'].agg(['mean','count']).reset_index()

geo_hour_stats['smooth'] = (
    geo_hour_stats['mean'] * geo_hour_stats['count'] +
    global_mean * 30
) / (geo_hour_stats['count'] + 30)

In [46]:
train = train.merge(
    geo_hour_stats[['geohash','hour','smooth']],
    on=['geohash','hour'],
    how='left'
)

test = test.merge(
    geo_hour_stats[['geohash','hour','smooth']],
    on=['geohash','hour'],
    how='left'
)

In [47]:
train['geo_hour_smooth'] = train['smooth'].fillna(global_mean)
test['geo_hour_smooth'] = test['smooth'].fillna(global_mean)

In [48]:
train.drop(columns=['smooth'], inplace=True)
test.drop(columns=['smooth'], inplace=True)

In [49]:
FEATURES = [
    'hour','minute','time_block','hour_sin','hour_cos',
    'NumberofLanes','Temperature','RoadType','Weather',
    'LargeVehicles','Landmarks',
    'geo_mean','geo_hour_smooth',
    'lag_1','lag_2','roll_mean_3'
]

In [50]:
model.fit(X_tr, y_tr)
preds = model.predict(X_val)

from sklearn.metrics import r2_score
print("R2:", r2_score(y_val, preds))

R2: 0.798423618648748

In [51]:
from xgboost import XGBRegressor

model = XGBRegressor(
    n_estimators=4000,
    learning_rate=0.02,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    min_child_weight=7,
    gamma=0.3,
    reg_alpha=0.5,
    reg_lambda=3.0,
    tree_method='hist',
    random_state=42,
    n_jobs=-1
)

model.fit(X_tr, y_tr)

preds = model.predict(X_val)

from sklearn.metrics import r2_score
print("R2:", r2_score(y_val, preds))

R2: 0.8027437783064378

In [52]:
print(train[FEATURES].dtypes)
print(train[FEATURES].isnull().sum())

hour                 int64
minute               int64
time_block           int64
hour_sin           float64
hour_cos           float64
NumberofLanes        int64
Temperature        float64
RoadType             int32
Weather              int32
LargeVehicles        int32
Landmarks            int32
geo_mean           float64
geo_hour_smooth    float64
lag_1              float64
lag_2              float64
roll_mean_3        float64
dtype: object
hour                  0
minute                0
time_block            0
hour_sin              0
hour_cos              0
NumberofLanes         0
Temperature           0
RoadType              0
Weather               0
LargeVehicles         0
Landmarks             0
geo_mean              0
geo_hour_smooth       0
lag_1              1249
lag_2              2466
roll_mean_3        3649
dtype: int64

In [53]:
train_clean = train.copy()

features_to_drop = ['lag_1', 'lag_2', 'roll_mean_3']

train_clean = train_clean.drop(columns=features_to_drop)
test_clean = test.drop(columns=features_to_drop)

KeyError: "['lag_1', 'lag_2', 'roll_mean_3'] not found in axis"

In [54]:
FEATURES = [
    'hour', 'minute', 'time_block', 'hour_sin', 'hour_cos',
    'NumberofLanes', 'Temperature',
    'RoadType', 'Weather', 'LargeVehicles', 'Landmarks',
    'geo_mean', 'geo_hour_smooth'
]

In [55]:
features_to_drop = ['lag_1', 'lag_2', 'roll_mean_3']

train_clean = train.drop(columns=features_to_drop)


test_clean = test.drop(columns=features_to_drop, errors='ignore')

In [56]:
train_clean = train.drop(columns=['lag_1','lag_2','roll_mean_3'])
test_clean = test.drop(columns=['lag_1','lag_2','roll_mean_3'], errors='ignore')

In [57]:
FEATURES = [
    'hour', 'minute', 'time_block', 'hour_sin', 'hour_cos',
    'NumberofLanes', 'Temperature',
    'RoadType', 'Weather', 'LargeVehicles', 'Landmarks',
    'geo_mean', 'geo_hour_smooth'
]

In [58]:
model.fit(
    train_clean[train_clean['day']==48][FEATURES],
    train_clean[train_clean['day']==48]['demand']
)

preds = model.predict(
    train_clean[train_clean['day']==49][FEATURES]
)

from sklearn.metrics import r2_score
print("R2:", r2_score(
    train_clean[train_clean['day']==49]['demand'],
    preds
))

R2: 0.8385232654370413

In [59]:
y_tr_log = np.log1p(y_tr)
y_val_log = np.log1p(y_val)

model.fit(X_tr, y_tr_log)

pred_log = model.predict(X_val)

pred = np.expm1(pred_log)

from sklearn.metrics import r2_score
print("R2:", r2_score(y_val, pred))

R2: 0.8030373577465523